### ISSUE TITLE
CodeAuditor unable to push and fetch scan results 

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#103]
As my conversation with @christianmorfordwaitessw , CodeAuditor was found to be unable to push nor fetch data from the database server. 
This could be due to related CORS issue with the Firebase server

![image](https://user-images.githubusercontent.com/67776356/99743981-ee34f180-2b2a-11eb-8a94-e73aff5c4b63.png)
**Figure: CodeAuditor unable to push data** 

![image](https://user-images.githubusercontent.com/67776356/99744196-54ba0f80-2b2b-11eb-853a-dfb9caa2377a.png)
**Figure: CORS issue when trying to fetch data**

**Comment by tombui99** [comment]
This issue has been fixed by updating Firebase Server

**Comment by christianmorfordwaitessw** [comment]
Thanks @tombui99,

My scans are uploading okay
