### ISSUE TITLE
🐛  BUG: CodeAuditor unable to run on SSW Rules

### ISSUE THREAD

**Issue by adamcogan** [SSWConsulting/SSW.CodeAuditor#105]
TO: @tombui99 
CC: @christianmorfordwaitessw 
CC: @nvhoanganh 

Cannot scan www.SSW.com.au/rules
It gives an error and doesn't continue scanning. It fails on the home page.
Note: It does however work from a category page

-a
www.adamcogan.com

**Comment by tombui99** [comment]
TO: @adamcogan 
CC: @christianmorfordwaitessw 
CC: @nvhoanganh 

Hi @adamcogan,

> Cannot scan www.SSW.com.au/rules
- Done - This issue has been fixed and CodeAuditor is now able to scan on SSW Rules V2

![image](https://user-images.githubusercontent.com/67776356/101591859-67947580-3a41-11eb-85f9-7fecd9623d21.png)
**Figure: SSW Rules's [CodeAuditor scan result](https://codeauditor.com/build/49e4509f-b47d-41fc-eacb-7ade8e3cdd3f)**
