### ISSUE TITLE
BUG - CodeAuditor showing different number of broken links on SSW Rules

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#115]
TO: @tombui99 
CC: @adamcogan @nvhoanganh @AndreasLengkeek @bradystroud 

As per our conversation, CodeAuditor's scan shows different results for SSW Rules in a week span
1. Investigate and find the cause
2. Fix and improve CodeAuditor to scan more consistently

![image](https://user-images.githubusercontent.com/67776356/102851280-7b8f9c80-446f-11eb-9f7b-5cbd60ef59c8.png)
**Figure: CodeAuditor finds 36 bad links on [15th December](https://codeauditor.com/build/d05742ee-a44c-4733-2a30-93f89955f3ca?displayMode=0)**

![image](https://user-images.githubusercontent.com/67776356/102851350-b396df80-446f-11eb-8f03-a6f2450ffcf8.png)
**Figure: CodeAuditor finds 140 bad links on [22nd December](https://codeauditor.com/build/60266449-1685-413f-2004-dc731d1124be?displayMode=0)**

**Comment by christianmorfordwaitessw** [comment]
Hi @tombui99,

On SSW Rules the number of scanned links has reduced to 17
![image](https://user-images.githubusercontent.com/56522256/104873419-94bf3680-59a4-11eb-85dd-65bd352c9dab.png)
**Figure: CodeAuditor only scanning 17 links on [18th January](https://codeauditor.com/build/ebdd2754-78e4-4f5c-5b3b-ee18ddda2a41)**

**Comment by tombui99** [comment]
Hi @christianmorfordwaitessw, @adamcogan, @nvhoanganh 

Consistency Improvement Updates - SSW Rules scans on CodeAuditor is getting more consistent, most scans have more than 10k scanned links

![image](https://user-images.githubusercontent.com/67776356/111095608-ed204800-8591-11eb-85c2-59be1dbe82f6.png)
**Figure: SSW Rules scan on CodeAuditor getting more consistent**

**Comment by bfabiny** [comment]
Estimate: 8

**Comment by tombui99** [comment]
To @bfabiny @christianmorfordwaitessw @adamcogan @bradystroud @pierssinclairssw @AndreasLengkeek 

> Fix CodeAuditor to produce consistent scan results on SSW Rules

Done - CodeAuditor's scan results on SSW Rules are now consistent

![image](https://user-images.githubusercontent.com/67776356/121618961-137b5400-caab-11eb-8c9e-f5956d9a3ddf.png)

**Figure: Latest SSW Rules scan results are consistent https://codeauditor.com/home**
