### ISSUE TITLE
DevOps - CI build failing on deploy

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.CodeAuditor#122]
cc @adamcogan @nvhoanganh 

CI build is failing on a deploy step and as a result releases are currently being done manually

![image](https://user-images.githubusercontent.com/600044/103385270-cdaa7f00-4b4d-11eb-8277-2fdef50da486.png)

1. Fix deployment action issue so that releases are automated

**Comment by tombui99** [comment]
TO: @wicksipedia 
CC: @adamcogan @nvhoanganh 

> Fix deployment action issue so that releases are automated

Done - Deployment is now successful, it was resolved by updating the Firebase Token and updating package-lock.json in Firebase functions folder
![image](https://user-images.githubusercontent.com/67776356/103977289-12c55580-51cd-11eb-9c3c-f9142c966942.png)
**Figure: Latest build is successful**

**Comment by tombui99** [comment]
Closed as this has been resolved
