### ISSUE TITLE
Code Auditor broken links check breaks when there are 3000 links

### ISSUE THREAD

**Issue by christianmorfordwaitessw** [SSWConsulting/SSW.CodeAuditor#13]
Code Auditor broken links check works fine when the number of links is small, but when there are 3000 links, we have this error : 
![image](https://user-images.githubusercontent.com/56522256/87366618-812db000-c5bc-11ea-8b1a-7aee81036665.png)

https://ssw.visualstudio.com/SSW.Rules/_build/results?buildId=20877&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=996a989a-edd9-5084-d9de-d81350de1bfc

https://sswrulesstaging1.firebaseapp.com/rules/

**Comment by nvhoanganh** [comment]
added flag which you can control how many concurrent threads are running for the SSW Link auditor

**Comment by christianmorfordwaitessw** [comment]
Hi @tombui99 ,

Closing this issue as we have moved our staging server on-prem and is no longer on firebase.
