### ISSUE TITLE
UI - Make Favicon consistent with logo + add tagline

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#133]
Hi Code Auditor team,

1. Can you make sure the Favicon on CodeAuditor.com is consistent with its logo?
<img width="448" alt="Screen Shot 2021-02-17 at 1 38 31 PM" src="https://user-images.githubusercontent.com/12601228/108271392-97d55000-7125-11eb-99e1-bcf9bf390c83.png">

2. The title should also include a tagline (Not sure if it has one already but I didn't find it on the homepage...)
eg. SSW CodeAuditor | Keep your code clean

**Comment by tombui99** [comment]
Hi Tiago,

    > Can you make sure the Favicon on CodeAuditor.com is consistent with its logo?
Done 

    >The title should also include a tagline (Not sure if it has one already but I didn't find it on the homepage...)
eg. SSW CodeAuditor | Keep your code clean
Done 

![image](https://user-images.githubusercontent.com/67776356/110422944-5583ab00-80f4-11eb-8fde-cf8bcf1f23b2.png)
**Figure: More consistent Favicon and new page title**

**Comment by tombui99** [comment]
Closed as this item has been done
