### ISSUE TITLE
UI - add comma to big numbers

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#154]
To: @adamcogan 
CC: @bradystroud @JackLeerson 

(Checked by Jack and Brady)

As per our conversation, numbers over 1000 should have comma
1. Make big numbers have comma
![image](https://user-images.githubusercontent.com/67776356/111939143-941b5b80-8b1f-11eb-95c3-18e1cc9c0bdd.png)
**Figure: Scan data with big numbers**

**Comment by tombui99** [comment]
Done - Thousand separator added 

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/67776356/111945755-5a058600-8b2e-11eb-9a94-98dd3398b180.png">
**Figure: Thousand separator added**

**Comment by tombui99** [comment]
TO @tombui99

The scan number on the left does not have thousand separator
1. Please add comma to the scanned number on the left

**Comment by bfabiny** [comment]
Estimate: 1

**Comment by tombui99** [comment]
CC: @bfabiny 

> Please add comma to the scanned number on the left

Done - comma separator added to "Scanned" number

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/67776356/112266072-a2a47700-8cc7-11eb-9418-ef2fe7bdb22d.png">

**Figure: scanned number with comma separator**

**Comment by bfabiny** [comment]
Can we make the following changes:
1. Make all the titles to sentence case
2. Remove the decimal place in the Latency P95, add the thousands separator, and milliseconds
3. Update the format of the Duration to be 17m 26s

**Comment by tombui99** [comment]
> Make all the titles to sentence case

Done - See figure below

> Remove the decimal place in the Latency P95

Done - See figure below

> Add the thousands separator

Done - See figure below

> Add milliseconds unit eg. 1,303 ms

Done - See figure below

> Update the format of the Duration to be 17m 26s

Done - See figure below

> On the right of the Bad Links, there should be a small blue information "i" icon link which describes the two values.

Not Done

![image](https://user-images.githubusercontent.com/67776356/120976667-e599c500-c7b5-11eb-8d40-58d652dd02dd.png)

**Figure: Updated Scan summary UI**
