### ISSUE TITLE
UI - change “code error“ title to something that makes more sense

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#155]
To: @adamcogan 
CC: @bradystroud @JackLeerson 

(Checked by Jack and Brady)

As per our conversation, the title for code errors is a bit confusing
1. Please change 
From
"CODE ERRORS"
To
"CODE WARNINGS"
2. Please change
From
"CODE WARNINGS"
To
"BAD CODE"

![image](https://user-images.githubusercontent.com/67776356/111939251-e197c880-8b1f-11eb-8f74-89e67ce055e3.png)
**Figure: Bad code titles**

**Comment by tombui99** [comment]
Done - Updated titles to make less confusing

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/67776356/111941464-37bb3a80-8b25-11eb-9b95-62aeb552cd83.png">
**Figure: Updated code title**

**Comment by tombui99** [comment]
TO @adamcogan 

Done - Title in card summary fixed to make clearer

<img width="432" alt="image" src="https://user-images.githubusercontent.com/67776356/120738094-9728c400-c532-11eb-9d47-b058c7b4ca3c.png">

**Figure: New title name in card summary**

**Comment by bfabiny** [comment]
To make it easier to understand and more consistent with Visual Studio, we should display the labels as "Errors" and "Warnings".

**Comment by tombui99** [comment]
Done - renamed title to "Errors" and "Warnings"

![image](https://user-images.githubusercontent.com/67776356/120976928-22fe5280-c7b6-11eb-944e-125faaf6b777.png)

**Figure: Renamed titles**
