### ISSUE TITLE
ENHANCEMENT - allow selecting html hint rules to check

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#157]
To: @adamcogan 
CC: @JackLeerson @bradystroud 

(Checked by Jack and Brady)

As per our conversation, there should be a feature on Codeauditor to allow user to select which HTML Rules to scan
1. Add a feature that let user select what HTML rules they want to check

<img width="1427" alt="Screen Shot 2021-03-23 at 11 55 49 am" src="https://user-images.githubusercontent.com/67776356/112076669-f8e1bf00-8bce-11eb-8fd8-a72c9733b4d2.png">

**Figure: New Set HTML Rules button**

![image](https://user-images.githubusercontent.com/67776356/112077261-3dba2580-8bd0-11eb-8277-0bd54ca1e720.png)

**List of HTML rules for the user to select**

**Comment by bfabiny** [comment]
- Redesign to be a page as there are a lot of HTML rules
- Each Rule should contain the name and brief description of the rule, with a link to the rules.
- Once the design is completed, get it checked by someone and get Adam to check it.

**Comment by tombui99** [comment]
Done - New feature to allow selecting html hint rules has been implemented

**Comment by tombui99** [comment]
Closed as this item has been done
