### ISSUE TITLE
UI - Footer covering up part of page

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#159]
cc: @JackLeerson 
Hi @tombui99,

The footer on the CodeAuditor UI is covering a small part of the page.

![2021-03-22_14-59-52](https://user-images.githubusercontent.com/38869720/111942879-01c78780-8b20-11eb-93fa-303643f61ecb.png)
**Figure: Content hidden by footer**

1. Fix the footer so it doesn't hide any content

Thanks,

-Brady

**Comment by tombui99** [comment]
Done - Fixed footer so it won't cover the bottom part of the page

![image](https://user-images.githubusercontent.com/67776356/111949037-1f065100-8b34-11eb-8d19-57b6dc4fef75.png)
**Figure: Footer not covering up part of page**

**Comment by tombui99** [comment]
Closed as this item has been done
