### ISSUE TITLE
Report - Update "Language-code-block-require" rule label

### ISSUE THREAD

**Issue by bfabiny** [SSWConsulting/SSW.CodeAuditor#169]
The label used on the report for the language code rule should be made clearer.

Change 
From 
   Language-code-block-require
To
   Code block - missing language

![image](https://user-images.githubusercontent.com/52905336/112249025-22701880-8cab-11eb-81f5-8b6660f90f6b.png)
**Figure: Rule name to change**

**Comment by tiagov8** [comment]
Hey @bfabiny 

1. The label should also be updated on [CodeAuditor Rules page](https://codeauditor.com/rules)
<img width="625" alt="Screen Shot 2021-04-01 at 3 53 41 PM" src="https://user-images.githubusercontent.com/12601228/113362145-88d7e500-9302-11eb-8a10-fb17a31a52a4.png">

2. Make sure all other issues are shown to the user with a friendly label. 
E.g.: **"alt-require"** should be **"Image - missing alt attribute"**

**Comment by bfabiny** [comment]
Hey Tiago,

Partially Done.

  1.  > The label should also be updated on CodeAuditor Rules page<https://codeauditor.com/rules>

[Screen Shot 2021-04-01 at 3 53 41 PM]<https://user-images.githubusercontent.com/12601228/113362145-88d7e500-9302-11eb-8a10-fb17a31a52a4.png>

Figure: Label not updated



Done – this was done as part of the implementation of the Agile Scrum Terms rule which has now been completed. See https://codeauditor.com/rules

***@***.***D72ADF.A0020700]

Figure: Updated Issue Labels

  1.  > Make sure all other issues are shown to the user with a friendly label.
E.g.: "alt-require" should be "Image - missing alt attribute"
Not Done – GitHub issue #199<https://github.com/SSWConsulting/SSW.CodeAuditor/issues/199> has been logged to fix this.

Thanks
Brad

**Comment by bfabiny** [comment]
Hey @tiagov8, 

Test Please:
Are the following friendly labels ok?

Current Rule | Friendly Text
--- | ---
"tagname-lowercase" | "HTML Tags - tag names must be lowercase"
"attr-lowercase" | "Attributes - attribute names must be lowercase" 
"attr-value-double-quotes" | "Attributes - attribute values must be in double quotes"
"attr-value-not-empty" | "Attributes - all attributes must have values"
"attr-no-duplication" | "Attributes - element cannot contain duplicate attributes"
"doctype-first" | "HTML - Doctype must be declared first"
"tag-pair" | "HTML Tags - tags must be paired"
"empty-tag-not-self-closed" | "HTML Tags - an empty tag should not be closed by itself"
"spec-char-escape" | "HTML - special characters must be escaped"
"id-unique" | "HTML Tags - id attribute must be unique"
"src-not-empty" | "Image - the src attribute must have a value"
"title-require" | "HTML - title tag must be present"
"alt-require" | "Image - missing alt attribute"
"doctype-html5" | "HTML - Doctype must be HTML5"
"style-disabled" | "CSS - style tags cannot be used"
"inline-style-disabled" | "HTML - Inline style cannot be used"
"inline-script-disabled" | "HTML - Inline script cannot be used"
"id-class-ad-disabled" | "HTML Tags - id and class cannot use the ad keyword"
"href-abs-or-rel" | "Links - href attribute must be either absolute or relative"
"attr-unsafe-chars" | "Attributes - attributes cannot contain unsafe characters"
"head-script-disabled" | "HTML - the script tag cannot be used in another tag"

**Comment by tiagov8** [comment]
Hi @bfabiny 

Looking good. Below are a few small changes in bold:

Current Rule | Friendly Text
-- | --
"tagname-lowercase" | "HTML Tags - tag names must be lowercase"
"attr-lowercase" | "Attributes - attribute names must be lowercase"
"attr-value-double-quotes" | "Attributes - attribute values must be in double quotes"
"attr-value-not-empty" | "Attributes - all attributes must have values"
"attr-no-duplication" | "Attributes - element cannot contain duplicate attributes"
"doctype-first" | "HTML - **DOCTYPE** must be declared first"
"tag-pair" | "HTML Tags - tags must be paired"
"empty-tag-not-self-closed" | "HTML Tags - an empty tag should not be closed by itself"
"spec-char-escape" | "HTML - special characters must be escaped"
"id-unique" | "HTML Tags - id attribute must be unique"
"src-not-empty" | "**Images** - the src attribute must have a value"
"title-require" | "HTML **Tags** - **missing title tag**"
"alt-require" | "**Images** - missing alt attribute"
"doctype-html5" | "HTML - **DOCTYPE**  must be HTML5"
"style-disabled" | "**HTML / CSS** - **style** tags **should not** be used"
"inline-style-disabled" | "HTML - **inline** **styling** **should not** be used"
"inline-script-disabled" | "HTML - **inline** script **should not** be used"
"id-class-ad-disabled" | "HTML Tags - id and class cannot use the ad keyword"
"href-abs-or-rel" | "Links - href attribute must be either absolute or relative"
"attr-unsafe-chars" | "Attributes - attributes cannot contain unsafe characters"
"head-script-disabled" | "HTML - the script tag cannot be used in another tag"

---

BTW - This one should be changed too...
from:

Issue | SSW Rule | Description
-- | -- | --
Code block - missing language | Markdown – Do you set rules on code blocks | Code blocks must contain a language specifier.
Common Agile Scrum Terms people get wrong | Scrum should be capitalized | Pages that reference Agile Scrum must have correct case for Scrum terminology.


to:

Issue | SSW Rule | Description
-- | -- | --
Code block - missing language | Markdown – Do you set rules on code blocks **?** | Code blocks must contain a language specifier.
**Grammar mistake - common Scrum terms** | **Grammar - Do you know "Scrum" should be capitalized?** | **References to "Agile Scrum" must be capitalized as "Scrum".**

**Comment by bfabiny** [comment]
> Hey @bfabiny
> 
> 1. The label should also be updated on [CodeAuditor Rules page](https://codeauditor.com/rules) (not only on reports)
> 
> <img alt="Screen Shot 2021-04-01 at 3 53 41 PM" width="625" src="https://user-images.githubusercontent.com/12601228/113362145-88d7e500-9302-11eb-8a10-fb17a31a52a4.png">
> 
> 2. Make sure all other issues are shown to the user with a friendly label.
>    E.g.: **"alt-require"** should be **"Image - missing alt attribute"**

1. Done - see https://codeauditor.com/rules
![image](https://user-images.githubusercontent.com/52905336/114112890-b20afd80-9920-11eb-936f-0b6dde61d46d.png)
**Figure: Updated CodeAuditor Rules page**

2. Done
![image](https://user-images.githubusercontent.com/52905336/114113015-0ca45980-9921-11eb-92dc-fe95c3a2b4cc.png)
**Figure: Updated friendly labels for CodeAuditor rules**

**Comment by tiagov8** [comment]
Hey @bfabiny ,

Sorry I have one more change:

from

"inline-style-disabled" | "HTML - inline styling should not be used"
-- | --
"inline-script-disabled" | "HTML - inline script should not be used"

to

"inline-style-disabled" | "HTML **/ CSS** - inline styling should not be used"
-- | --
"inline-script-disabled" | "HTML **/ JS** - inline script should not be used"

For consistency ;)
