### ISSUE TITLE
CodeAuditor.com - Add new page - How it Works

### ISSUE THREAD

**Issue by bfabiny** [SSWConsulting/SSW.CodeAuditor#170]
On the CodeAuditor website: https://codeauditor.com/

1. Add a new page "How it works"

The page should contain a high level description of how Code Auditor works by scanning all of the code in the website against all the "CodeAuditor Rules" and displays the results as "CodeAuditor Issues" which can be addressed.

2. The page should be added to the Menu next to the Explore item.
![image](https://user-images.githubusercontent.com/52905336/112252734-bb099700-8cb1-11eb-8692-6b401976950a.png)
**Figure: Place the new page next to the Explore menu item**

3. The home page should be more designer appealing, maybe with a video embedded in it.

**Comment by tombui99** [comment]
Closed as this item has been done
