### ISSUE TITLE
FOOTER - duplicated links

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#191]
Hi team,

We have duplicated information on the footer:

- Copyright (green)
- Twitter (orange)

<img width="1642" alt="Screen Shot 2021-03-30 at 8 58 26 AM" src="https://user-images.githubusercontent.com/12601228/113019798-d273d480-9136-11eb-9ef1-87430d07cd64.png">

I would remove the ones next to CodeAuditor logo

1. Please action if the team agrees

Tiago

**Comment by tombui99** [comment]
Hi @tiagov8 

> Please action if the team agrees

Done - it was agreed duplicated links on footer
![image](https://user-images.githubusercontent.com/67776356/113082192-bb5fe000-9225-11eb-8dda-60f554006d48.png)
**Figure: Footer without duplicated links**

**Comment by tombui99** [comment]
Closed as this item is done
