### ISSUE TITLE
HEADER UI - Inconsistent colour on username hover

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#192]
Team,

1. Please fix the green on hover to be SSW's red #CC4141

<img width="299" alt="Screen Shot 2021-03-30 at 9 28 07 AM" src="https://user-images.githubusercontent.com/12601228/113023402-6b581f00-913a-11eb-9453-42a39516729a.png">

**Comment by tombui99** [comment]
> Please fix the green on hover to be SSW's red #CC4141

Done - changed color when hover on user menu

![image](https://user-images.githubusercontent.com/67776356/113082129-9f5c3e80-9225-11eb-9ccd-0aa6d9029199.png)

**Figure: User menu options when hovered**

**Comment by tombui99** [comment]
Closed as this item is done
