### ISSUE TITLE
HEADER UI - Improvements to menu items

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#193]
**Hi team,**

I'm not 100% happy with the current nav look and feel + scalability...

What do you think about changing from:

<img width="1160" alt="Screen Shot 2021-03-30 at 9 34 02 AM" src="https://user-images.githubusercontent.com/12601228/113024086-339da700-913b-11eb-92bb-45815b5b7a0a.png">

to something like:

<img width="1160" alt="Screen Shot 2021-03-30 at 9 34 02 AM" src="https://user-images.githubusercontent.com/12601228/113026195-aad43a80-913d-11eb-98aa-b36bd3bc4b43.png">

1. Please implement if you agree

--

2. Please also make the dark grey darker by changing 

from:
```
.nav.svelte-knxqi7, footer.svelte-knxqi7 {
    background-color: #414141;
}
```
to:
```
.nav.svelte-knxqi7, footer.svelte-knxqi7 {
    background-color: #333;
}
```

**Comment by tombui99** [comment]
Hi @tiagov8 

> Please implement if you agree

Done - it was agreed to implement the changes

![image](https://user-images.githubusercontent.com/67776356/113081924-56a48580-9225-11eb-8d32-dcb4ef8bc652.png)
**Figure: New Header UI**

> Please also make the dark grey darker 

Done 

![image](https://user-images.githubusercontent.com/67776356/113081993-6de37300-9225-11eb-95e0-50c421cb03e4.png)
**Figure: new background color for navbar and footer**

**Comment by tombui99** [comment]
Closed as this item has been done
