### ISSUE TITLE
New page - How to create a new CodeAuditor rule?

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#208]
Hi team,

as per my conversation with @adamcogan 

1. Create a new page showing how to create a new CodeAuditor rule
This is to replace the old: https://www.ssw.com.au/ssw/CodeAuditor/RegExTutorial.aspx

2. When done, tell Tiago to add a redirect from the old page

**Comment by tombui99** [comment]
Hi @tiagov8 

> Create a new page showing how to create a new CodeAuditor rule

Done - New section created to instruct how to add custom HTML Hint rules

> When done, tell Tiago to add a redirect from the old page

Done

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/67776356/122488219-5647a980-d020-11eb-8a71-026612e3a34c.png">

**Figure: How to add custom rule section**
