### ISSUE TITLE
Could CodeAuditor running against SQL RS?

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#209]
Hi team, 

1. Can CodeAuditor run against SQL RS?
This would replace: https://www.ssw.com.au/ssw/CodeAuditor/rsuserguide.aspx

@adamcogan Please provide more information if needed

--

Related: #210

**Comment by tombui99** [comment]
Hi @tiagov8 

CodeAuditor cannot run against SQL RS as it is not a Static Website
