### ISSUE TITLE
Improvements to CodeAuditor Homepage

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#211]
Hi @tombui99 ,

https://codeauditor.com/home

- [x] Please add a "Home" link on the menu, before "Explore"
- [x] Change heading from "Instruction to scan an URL" to "**Instructions** to scan an URL" 
- Also need to be changed on https://codeauditor.com/howitworks
- [x] Change heading from "System Requirements" to "System requirements" (for consistency)
- [x] For the "More Options" and "Collapse" links
- Can we add + and - icons next to them? https://fontawesome.com/icons/minus-square?style=solid and https://fontawesome.com/icons/plus-square?style=solid
- Can we make it a button (I think just need to add the class "btn" from tailwind) so it has a background and stands out from the normal text?
- And change from "collapse" to "Less Options"

**Comment by tombui99** [comment]
Hi @tiagov8 

> Please add a "Home" link on the menu, before "Explore"

Done - Added "Home" link before "Explore"

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/67776356/122310259-529a2100-cf53-11eb-9cac-2e3977597c83.png">

**Figure: Added Home link before Explore**

> Change heading from "Instruction to scan an URL" to "Instructions to scan an URL"

Done - Changed heading to "Instructions to scan an URL"

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/67776356/122310287-69407800-cf53-11eb-8ebc-a137db450fae.png">

**Figure: Changed heading to "Instructions to scan an URL"**

> Change heading from "System Requirements" to "System requirements" (for consistency)

Done - Changed heading to "System requirements"

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/67776356/122310330-78bfc100-cf53-11eb-8294-3eecb27221d6.png">

**Figure: Changed heading to "System requirements"**

> For the "More Options" and "Collapse" links. Can we add + and - icons next to them? 
Can we make it a button (I think just need to add the class "btn" from tailwind) so it has a background and stands out from the normal text? And change from "collapse" to "Less Options"

Done - Modified "More Options" and "Less Options" design

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/67776356/122310373-8bd29100-cf53-11eb-9cc2-6538774c77fe.png">

**Figure: New "More Options" button**

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/67776356/122310387-92f99f00-cf53-11eb-966a-5fe255d3757e.png">

**Figure: New "Less Options" button**
