### ISSUE TITLE
Feature - Update to include protocol validation in URL parameter

### ISSUE THREAD

**Issue by bfabiny** [SSWConsulting/SSW.CodeAuditor#212]
When running CodeAuditor, if the url passed to it does not contain the protocol an error is displayed when performing the Artillery load test.

![image](https://user-images.githubusercontent.com/52905336/115138066-2eae8200-a06d-11eb-8af6-691bb5ad3f7f.png)
**Figure: Error displayed when no protocol listed.**

To make this clearer, we should 
- [x] Update the instructions to tell users to include the full URL and provide an example
Change 
From 
![image](https://user-images.githubusercontent.com/52905336/115138149-cf9d3d00-a06d-11eb-9ee9-4554b131f295.png)
**Figure: SSW CodeAuditor; How it Works**
To
4. Open Windows Powershell and paste the above command, replace <URL> with the full url you want to test. eg. https://www.ssw.com.au/rules

- [x] Update CodeAuditor to validate that the url parameter has the correct format.
- [ ] If no protocol (e.g. https) on the URL, automatically append "https"

**Comment by tombui99** [comment]
Hi @bfabiny 

> Update the instructions to tell users to include the full URL and provide an example

Done - updated instruction to include full URL

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/67776356/122328472-137bc800-cf73-11eb-83df-a5cdfe608f82.png">

**Figure: Updated instruction**

> Update CodeAuditor to validate that the url parameter has the correct format.

Done - Updated CodeAuditor to check if url is insufficient

<img width="566" alt="image" src="https://user-images.githubusercontent.com/67776356/122328384-e62f1a00-cf72-11eb-940f-ee4706efbdcb.png">

**Figure: CodeAuditor logs an error if the URL is insufficient**

**Comment by tombui99** [comment]
> If no protocol (e.g. https) on the URL, automatically append "https"

Done - if no protocol then auto append "https"
