### ISSUE TITLE
🐛 Bug - Blocked - Working links (such as Nuget.org) are being reported as 404 by CodeAuditor

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#215]
Hi team,

I noticed CodeAuditor reports are often showing working nuget.org links as broken... 

<img width="1248" alt="Screen Shot 2021-04-27 at 5 14 43 PM" src="https://user-images.githubusercontent.com/12601228/116327847-7c696f80-a77c-11eb-8ba6-032ff2d26aa2.png">

Rule: https://www.ssw.com.au/rules/do-you-know-the-code-health-quality-gates-to-add
Reported link: https://www.nuget.org/packages/tslint/

1. Please investigate and fix

**Comment by tiagov8** [comment]
Confirming the above, the 4 links found as broken in [this CodeAuditor report]( https://codeauditor.com/build/e213c01a-b155-44c5-44ad-c81924bf0351) are examples of this issue:

<img width="1387" alt="Screen Shot 2021-04-29 at 5 11 18 PM" src="https://user-images.githubusercontent.com/12601228/116633309-039a1d00-a90e-11eb-8c05-f8da9d67019d.png">

**Comment by tiagov8** [comment]
Similar problem is happening to these domains too (examples below):

- https://support.google.com/webmasters/answer/156184?hl=en
- https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens
- https://playwright.dev/docs/actionability/
- https://www.theurlist.com/xamarinstreamers

**Comment by tiagov8** [comment]
Hi Tom,
Still getting this one:

<img width="1193" alt="Screen Shot 2022-06-27 at 1 45 54 PM" src="https://user-images.githubusercontent.com/12601228/176033148-42757534-ebe3-4644-8934-a0f710cc2956.png">

Link works fine: https://dev.botframework.com/

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @adamcogan 

> Please fix 

Done - I have added the two links (https://dev.botframework.com/ and https://www.theurlist.com/xamarinstreamers) to the ignored list

Please find following link the latest scan on SSW Rules
https://codeauditor.com/build/43116ebc-38af-4307-387e-dd96f6c70236

1. Can you check the scan result and fix the broken links accordingly?

Thanks,
Tom
