### ISSUE TITLE
BUG: When browsing to Lighthouse Audit the breadcrumb show Undefined

### ISSUE THREAD

**Issue by ozdemir-mehmet** [SSWConsulting/SSW.CodeAuditor#22]
Browsing to Links or Code the scan GUID shows in the bread crumb:
![image](https://user-images.githubusercontent.com/37358029/88769171-6f086000-d1bf-11ea-9911-c8a3988d16a4.png)

But when browsing to Lighthouse the scan GUID is undefined (BUG)
![image](https://user-images.githubusercontent.com/37358029/88769327-9bbc7780-d1bf-11ea-8480-c9d3518a1d32.png)

**Comment by tombui99** [comment]
(Adding done comment)

Done - This has been fixed to show the run ID of the scan

![image](https://user-images.githubusercontent.com/67776356/110420349-35052200-80ef-11eb-8700-8c6ed1229c3a.png)
**Figure: Run id shown in breadcrumb**
