### ISSUE TITLE
Wiki - Add a Wiki

### ISSUE THREAD

**Issue by bfabiny** [SSWConsulting/SSW.CodeAuditor#237]
TO: @william-liebenberg, @nvhoanganh, @adamcogan, @ozdemir-mehmet, @miichaelsmedley, @bfabiny, @tombui99 
CC: @wicksipedia @pierssinclairssw 

Every project should have a Wiki.

1. Add a CodeAuditor Wiki repository that includes:
- [x] The reason why we chose to implement in Golang, Node.js and HTMLHint  (ie. we chose Node.js because HTMLHint uses it) 
- [x] Is this the correct way to implement rules checking?
- [x] Are there any other libraries which Microsoft have developed which could replace the current HTMLHint
- [x] Create a new architecture diagram
- [x] Add more evidences as to why Golang is the best tool for scanning bad links ( include Google Trend links )
- [ ] Investigate why we chose Golang over C# otherwise remove it

**Comment by bfabiny** [comment]
From Anthony:
"Golang is used because it is the best at multi-threading and handles it better than other languages. There was already an example of scanning a site for broken links in Golang."

**Comment by tombui99** [comment]
Hi @bfabiny 

Done - CodeAuditor Wiki added

<img width="961" alt="image" src="https://user-images.githubusercontent.com/67776356/122312747-38af0d00-cf58-11eb-8b76-c74614db3a5b.png">

**Figure: New Wiki for CodeAuditor**

**Comment by tombui99** [comment]
CC @adamcogan @wicksipedia @nvhoanganh @pierssinclairssw 

Not Done - add more evidences as to why Golang is the best tool for scanning bad links
E.g. Google Trend links

**Comment by tombui99** [comment]
> Add more evidences as to why Golang is the best tool for scanning bad links

Done - added evidences (checked by @nvhoanganh )

<img width="915" alt="image" src="https://user-images.githubusercontent.com/67776356/122873152-c33aa680-d374-11eb-8bcc-d7774e09c914.png">

**Figure: More evidence why we use golang**
