### ISSUE TITLE
Links to Rules should be consistent

### ISSUE THREAD

**Issue by bfabiny** [SSWConsulting/SSW.CodeAuditor#238]
TO: @william-liebenberg, @nvhoanganh, @adamcogan, @ozdemir-mehmet, @miichaelsmedley, @bfabiny, @tombui99 

On the Scan Results, the links to the rules in the Issues correctly link to either the HTMLHint rule, or, in the case of custom rules, to the associated SSW Rule.

In the "HTML Rules Scanned" in the summary section, the link to the rule only links to HTMLHint, and displays broken links to Custom SSW Rules. 
1. Links in this section should be changed to be consistent with the Scan Results.
2. Link text should use the discription ie "HTML / CSS - inline styling should not be used" instead of "inline-styling-disabled"

**Comment by tombui99** [comment]
> Links in this section should be changed to be consistent with the Scan Results.

Done - Fixed links to not navigate to 404 error pages

> Link text should use the discription ie "HTML / CSS - inline styling should not be used" instead of "inline-styling-disabled"
Done

Done - Fixed links to be displayed in same format as scan result list

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/67776356/121612512-e07e9380-ca9d-11eb-8988-1c1fc50a7865.png">

**Figure: New consistent UI to display links https://codeauditor.com/htmlhint/009e8cd3-7c01-4400-169c-35617f7a56c2**
