### ISSUE TITLE
Colour Code Results

### ISSUE THREAD

**Issue by bfabiny** [SSWConsulting/SSW.CodeAuditor#239]
CC: @nvhoanganh @bfabiny, @miichaelsmedley, @tombui99, @william-liebenberg, @ozdemir-mehmet, @adamcogan 

In the Summary section, the display of results should be consistent.
1. Any Errors counts should be displayed in red
2. Whenever there are 0 errors or warnings the "0" should be displayed in light grey (or black if that is not possible).

![image](https://user-images.githubusercontent.com/52905336/120763974-17fbb600-c55b-11eb-9f78-cb1cb59812a3.png)
**Figure: CodeAuditor Results with highlighted fields that should be colour-coded **

**Comment by tombui99** [comment]
> Any Errors counts should be displayed in red

Done - Errors more than 0 are displayed in red 

> Whenever there are 0 errors or warnings the "0" should be displayed in light grey (or black if that is not possible).

Done - Zero error are displayed in light grey

<img width="706" alt="image" src="https://user-images.githubusercontent.com/67776356/121612193-3bfc5180-ca9d-11eb-8426-3b45c516b49f.png">

**Figure: New color code result UI**

**Comment by bfabiny** [comment]
1. Add a grey tooltip indicating what a "Code Error" is and what a "Code Warning" is
2. Indent the results by 4 spaces
3. Add a grey tick next to the Bad Links when it is 0.

**Comment by tombui99** [comment]
Hi @bfabiny 

> Add a grey tooltip indicating what a "Code Error" is and what a "Code Warning" is

Done - Added to tooltip to reveal full info

<img width="670" alt="image" src="https://user-images.githubusercontent.com/67776356/122311150-e6b8b800-cf54-11eb-8e32-45fce47ceaa3.png">

**Figure: New tooltip messages**

> Add a grey tick next to the Bad Links when it is 0.

Done - Added grey tick next to Bad Links when it is 0

<img width="827" alt="image" src="https://user-images.githubusercontent.com/67776356/122311196-fdf7a580-cf54-11eb-8c1a-c6c6f2c595af.png">

**Figure: Added grey ticks**

> If the "Bad Links" numbers are the same, hide one of them.

Done - Hide Total Links when it is equal to Unique Links

<img width="405" alt="image" src="https://user-images.githubusercontent.com/67776356/122311223-0f40b200-cf55-11eb-86ce-ea633a2bd48d.png">


**Figure: Hidden Total Links when it is equal to Unique Links**
