### ISSUE TITLE
Enhancement: Show me the HTML snippet where the bad link occured

### ISSUE THREAD

**Issue by ozdemir-mehmet** [SSWConsulting/SSW.CodeAuditor#24]
When a broken link is shown in the report, show me a snippet of the html where this occured, or maybe the line number and horizontal position:

![image](https://user-images.githubusercontent.com/37358029/88769892-5c425b00-d1c0-11ea-886f-a2def05547e8.png)

**Comment by tiagov8** [comment]
hey @ozdemir-mehmet, can you please fix the typo on the title of this issue (snippe**n**t)? Cheers!
