### ISSUE TITLE
Change output from "audit fail" to "audit complete", and add some details

### ISSUE THREAD

**Issue by calumjs** [SSWConsulting/SSW.CodeAuditor#25]
![image](https://user-images.githubusercontent.com/13717390/88984311-9a4e9480-d310-11ea-99b6-502de0c23b58.png)
The output "AUDIT FAIL" sounds more like the audit itself failed rather than the audit completed and the result was fail.

I think we should do something like this (use “complete” rather than “failed”, give a quick summary breakdown of the results):

SSW Code Auditor - Scan Complete
Broken links: 7/310 - FAIL
Performance: 81/100 - FAIL
Accessibility: 100/100 - PASS
...etc

**Comment by tombui99** [comment]
(Adding Done comment)
![image](https://user-images.githubusercontent.com/67776356/110403802-db422f00-80d1-11eb-9ee1-6699692ddac6.png)
**Figure:: New message output**
