### ISSUE TITLE
UI - Enhance Rules Selection Popup

### ISSUE THREAD

**Issue by bfabiny** [SSWConsulting/SSW.CodeAuditor#252]
CC: @adamcogan, @nvhoanganh, @bfabiny, @tombui99, @pierssinclairssw 

Enhance the "Rules Selection for next scan" popup
1. Make it scrollable
2. Change the list to a grid, to add sorting and filtering
3. Review with a designer
4. Also consider the Rules scanned in the current scan.

**Comment by tombui99** [comment]
As per my conversation with Ken, this will be the new layout for Rules Selection Popup:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/67776356/123180425-94d0de80-d4ce-11eb-9e35-34629b2e4027.png)

**Figure: New Rules Selections Popup Mockup**
