### ISSUE TITLE
Create Beautiful Readme.md for Code Auditor

### ISSUE THREAD

**Issue by nvhoanganh** [SSWConsulting/SSW.CodeAuditor#26]
take examples from https://github.com/matiassingers/awesome-readme

we want our README to be as good as those because we want to give developers good impression

Need to:
- find a good logo for the app (talk to Rebecca)
- follow the best practice and write up the instructions on how to:
	- clone 
	- run the project
	- how to contribute
- show build badges

**Comment by tombui99** [comment]
(Adding Done comment)

https://github.com/SSWConsulting/SSW.CodeAuditor
**Link: CodeAuditor github page with new README**
