### ISSUE TITLE
UI polish and improvement

### ISSUE THREAD

**Issue by nvhoanganh** [SSWConsulting/SSW.CodeAuditor#27]

**Comment by tombui99** [comment]
(Adding Done comment)

- Changed the user interface on the build list page from table to cardviews
- Grouped the card items based on the URL scanned
- Added Drop down list to display the details each scan based on the URL
- Added Artillery load test result page
- Customized the BuildDetails and HTMLHINT pages to look similar to the mockups
- Added ChartJS components to display previous scans in bar charts

### Home Page
BEFORE
<img src="https://user-images.githubusercontent.com/67776356/90588473-0db43980-e21f-11ea-8ea1-c3b8c098925b.png" width="900"/>

AFTER
![image](https://user-images.githubusercontent.com/67776356/110405925-7e487800-80d5-11eb-85a4-9a2738df5c58.png)
Expand to view more scans on the same URL
![image](https://user-images.githubusercontent.com/67776356/110406268-0c246300-80d6-11eb-9d7c-06a96ad45afa.png)

### Build Page (Bad Links)
BEFORE
<img src="https://user-images.githubusercontent.com/67776356/90588601-5cfa6a00-e21f-11ea-882f-f33d672e59ac.png" width="900"/>

AFTER
![image](https://user-images.githubusercontent.com/67776356/110406029-aafc8f80-80d5-11eb-89cd-409901c4ec11.png)

### Build Page (Bad Codes)
BEFORE
<img src="https://user-images.githubusercontent.com/67776356/90588612-61bf1e00-e21f-11ea-854b-509b700fc0a1.png" width="900"/>

AFTER
![image](https://user-images.githubusercontent.com/67776356/110406076-bd76c900-80d5-11eb-828a-df7cd6032499.png)

### Lighthouse Audit Result Page
BEFORE
<img src="https://user-images.githubusercontent.com/67776356/90588613-64ba0e80-e21f-11ea-9669-7c17070176d0.png" width="900"/>

AFTER
![image](https://user-images.githubusercontent.com/67776356/110406174-e9924a00-80d5-11eb-8268-7578c0ca0eca.png)

### New Artillery Load Test page
![image](https://user-images.githubusercontent.com/67776356/110406119-d3848980-80d5-11eb-8bd5-6d71d9db26eb.png)
