### ISSUE TITLE
Add Artillery.io load test 

### ISSUE THREAD

**Issue by nvhoanganh** [SSWConsulting/SSW.CodeAuditor#28]
run 2 minutes Artillery load test on the target website and report it under lighthouse column

https://artillery.io/docs/cli-reference/

**Comment by tombui99** [comment]
Further requirements at the REST API level:
- save Artillery's raw JSON into "loadtest" bucket in storage account (similar to htmlhint, lighthouse)
- extract the "summary" out of this big JSON and save it to the "loadtest" field of the main scan entity 
- display this info some how on the first page and the details page

**Comment by tombui99** [comment]
a
