### ISSUE TITLE
✨ CodeAuditor Rule: when embedding YouTube video,  you should use the correct url

### ISSUE THREAD

**Issue by nvhoanganh** [SSWConsulting/SSW.CodeAuditor#313]
Cc: @tombui99 

Hi @tombui99 
  
### Pain

When user embed an YouTube video in to a website, they should use the correct url specifically created for embedding video.

Bad example  https://www.youtube.com/embed/zpTPQ34U8rc
 
Good example  https://www.youtube.com/watch?v=OccRyzAS4Vc

### Suggested Solution

Please create new rule in Code Auditor which check for this in the html

### Tasks

- [x] add new rule and check for https://www.youtube.com/watch? in the html
- [x] turn this rule on all SSW scans

### Screenshots

Thanks!

**Comment by tombui99** [comment]
Hi @nvhoanganh 

> add new rule and check for https://www.youtube.com/watch? in the html

Done - New custom rule added to check Youtube link

> turn this rule on all SSW scans

Done - The rule is turned on for all future scans

![image](https://user-images.githubusercontent.com/67776356/142359089-fb4dc80d-fe29-4d86-ac70-718bcb3e9d7e.png)

**Figure: New custom rule to check Youtube links**
