### ISSUE TITLE
🐛 UX - 'By Reason' accordion not working as expected

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#331]
Cc: @adamcogan 

Hi @tombui99 

### Describe the Bug
 When I click on any item to see more details using 'By Reason' view... the accordion opens ALL items, which is very confusing

### To Reproduce
1. Go to https://codeauditor.com/htmlhint/ebfa1d47-821f-4f16-4538-f168dec1d1a6?displayMode=1
2. Click on any specific reason
3. See error

Video showing the bug: https://youtu.be/ctApIxNscfs

### Expected Behavior
When clicking on an item, only that item opens up

### Tasks
- [x] Investigate
- [x] Fix

### Environment
 - Device: Mac
 - Browser: Chrome

Thanks!

**Comment by tombui99** [comment]
Hi Tiago, 

- [x] When clicking on an item, only that item opens up

Done - The bug has been fixed which now clicks on an item, only that item opens up

**Comment by tombui99** [comment]
Hi @tiagov8,
cc @adamcogan 

 When clicking on an item, only that item opens up
Done - The bug has been fixed which now clicks on an item, only that item opens up
