### ISSUE TITLE
✨ UI - Tell CodeAuditor to ignore some links (e.g. authentication needed)

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#343]
Cc: @adamcogan 

Hi @tombui99 
  
### Pain
CodeAuditor shows a 404 error for links that need authentication: 

E.g. On https://www.ssw.com.au/rules/have-a-google-places-entry there is a link to https://business.google.com/locations
If not logged in, user will be taken to https://accounts.google.com/signin/v2/identifier?service=lbc&passive=1209600&continue=https%3A%2F%2Fbusiness.google.com%2Flocations&followup=https%3A%2F%2Fbusiness.google.com%2Flocations&flowName=GlifWebSignIn&flowEntry=ServiceLogin

The links are not broken either way.

### Suggested Solution

Make CodeAuditor automatically recognize these links and keep out of reports
OR 
Allow the editors to tell CodeAuditor to ignore that link in Markdown (not sure what would be the best syntax)

### Tasks
- [ ] Investigate and implement the best solution

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8

> Implement CodeAuditor to ignore links

This feature has already been implemented in CodeAuditor

To ignore a link you simply need to click the slash circle icon next to the link

![image](https://user-images.githubusercontent.com/67776356/228727971-473ff071-b15f-4453-a896-a388a347e0da.png)

**Figure: Icon button to ignore link**

You can also have the option to set how long you want to ignore it for either just 3 days or permanently

![image](https://user-images.githubusercontent.com/67776356/228728057-16b3eb71-3504-4000-a054-dcabc5b0ace5.png)

**Figure: ignore link modal to set duration**

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan 

Closing this issue as it is already resolved

**Comment by tiagov8** [comment]
Hi @tombui99 

1. If someone choose "All new builds"... How do they revert it?
2. My request was a bit different. The way it is now you have to see the error, then action. I would like to tell in my code (any website) to say "Hey CodeAuditor, skip this link because I know it doesn't work". For example, then we can use www.northwind.com in our website examples; or for intranet links that we know require authentication. I see this as adding a class "codeauditor-ignore" for example. Is that doable?

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @adamcogan @william-liebenberg 

> If someone choose "All new builds"... How do they revert it?

The user can go to their "Ignored URLs" page and remove their ignored Urls

![image](https://user-images.githubusercontent.com/67776356/235421893-bed35b65-f5ca-43d2-bc73-ec2eb4a6e9ed.png)

**Figure: How you can navigate to your Ignored Urls list**

> This current solution allows only to ignore a whole page, but we need to ignore 1 single error occurance. 

Yes you can choose to either ignore a whole page or just one single link by using glob matching, e.g. `https://twitter.com/**` will match with `https://twitter.com/users/john` or `https://twitter.com/login`

We have this instruction on the Ignored Url modal

![image](https://user-images.githubusercontent.com/67776356/235421504-36c03936-ebab-4635-a0e3-d481619b796b.png)

**Figure: Instruction to ignore single link or entire page**

> A different scenario is if we decide to ignore 1 page based on 1 error, then it might have multiple errors that should be fixed...

This depends on whether the user wants to choose to scan on the website at all - We need to scan for broken links first and then the HTML

> My request was a bit different. The way it is now you have to see the error, then action. I would like to tell in my code in advance (any website) to say "Hey CodeAuditor, skip this link because I know what I am doing".

Done - I have added a new button in the Ignored list that let you choose which site you want to ignore from now on

![image](https://user-images.githubusercontent.com/67776356/235421033-59e84f15-79f1-4135-99f9-3044394b8501.png)

![image](https://user-images.githubusercontent.com/67776356/235421063-126e4ff8-b325-401c-b0bf-1584bc75cea6.png)

**Figure: New button in the Ignored Urls page to add links you want to ignore**

**Comment by william-liebenberg** [comment]
Hey @tombui99 

Is there a page that shows users all the supported glob patterns?

Which library are we using to support the glob pattern matching?

**Comment by tombui99** [comment]
Hi @william-liebenberg 

> Is there a page that shows users all the supported glob patterns?

Yes - You can go to the [minimatch npm library](https://www.npmjs.com/package/minimatch) page to see all the supported patterns.

The currently supported patterns are as follow:
- Brace Expansion
- Extended glob matching
- "Globstar" ** matching
- [Posix character classes](https://www.gnu.org/software/bash/manual/html_node/Pattern-Matching.html), like [[:alpha:]], supporting the full range of Unicode characters. For example, [[:alpha:]] will match against 'é', though [a-zA-Z] will not. Collating symbol and set matching is not supported, so [[=e=]] will not match 'é' and [[.ch.]] will not match 'ch' in locales where ch is considered a single character.

> Which library are we using to support the glob pattern matching?

We are using the [minimatch](https://www.npmjs.com/package/minimatch) library to support the glob pattern matching

**Comment by william-liebenberg** [comment]
Thats great Tom

But my question was if there was anything showing the CodeAuditor users how the glob patterns work. Imagine non-devs coming to CodeAuditor and they never heard of Glob patterns before. We need to show them how to use them somehow.

**Comment by tombui99** [comment]
Hey @william-liebenberg 

> If there was anything showing the CodeAuditor users how the glob patterns work. Imagine non-devs coming to CodeAuditor and they never heard of Glob patterns before. We need to show them how to use them somehow.

There is a small hint with an example under the Url text box that instructs how users can add their own glob pattern

![image](https://user-images.githubusercontent.com/67776356/235572923-4d338c8b-75fc-44c9-8e97-12fd13df4db3.png)

**Figure: Instruction hint on how to use glob pattern**

I'm more than happy to include more instruction in the "How It Works" page that shows all the glob patterns users can use. 

Let me know what you think!

**Comment by tombui99** [comment]
To @tombui99 

- [ ] Create a new Wiki page with supported Glob patterns and examples
