### ISSUE TITLE
🐛 UI - More options button not working

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#345]
Cc: @adamcogan 

Hi @tombui99 

### Describe the Bug

The More Options button on the home page doesn't work.

### To Reproduce
1. Go to https://codeauditor.com/
2. Click on More Options
3. The first section of the page dissapears

### Expected Behavior
More options are collapsed or I am navigated to more options

### Tasks
- [x] Investigate
- [x] Fix

Thanks!

**Comment by tombui99** [comment]
Hi @bradystroud 
cc @adamcogan 

> The More Options button on the home page doesn't work.

Done - The More Options button has been fixed so that the first section of the page does not disappear when it is clicked

**Comment by bradystroud** [comment]
@adamcogan 
Hey @tombui99

I just tested this and it still seems to be happening. 🤔

1. Please investigate

**Comment by bradystroud** [comment]
> Can you try clearing your browser's cache and try again?

Done - Fixed 🙂 

Thanks @tombui99 !
