### ISSUE TITLE
💄 General UI/UX feedback

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#346]
Cc: @adamcogan @tiagov8 

Hi @tombui99 
  
General UI/UX feedback
- Going to https://codeauditor.com/ and clicking Home go to different locations (Home requires auth)
	-  I expected home to be the same as the root page
- I am confused why I should create an account when it works perfectly without one?
	- I think I get extra functionality from an account, but im not sure
	- If this is the case, it should say that on the home page e.g. "CodeAuditor works fine without an account, but an account gives you access to these features: xxx, xxx, xxx"
- #345 
### Menu bar 
- Spacing doesn't look right
![Screen Shot 2022-05-31 at 5 56 29 pm](https://user-images.githubusercontent.com/38869720/171122604-bf174d93-08f8-42e4-94b9-0078cf67c189.png)
**Figure: No space on the left, gap on the right**
I think it should use bootstrap class [justify-content-between](https://getbootstrap.com/docs/4.0/utilities/flex/#justify-content) so menu items fill the space

### Displayed features on home page
These features should alternate which side the text is on
See https://www.gatsbyjs.com/ (scroll about 60% down the page) as an example
![Screen Shot 2022-05-31 at 6 04 32 pm](https://user-images.githubusercontent.com/38869720/171123925-9492e3b8-f031-4690-8468-b1659a566cb3.png)
**Figure: Text is always on the right and images are always on the left**

### Footer
- Social icons should have all the same links as SSW Rules, People and Website
![Screen Shot 2022-05-31 at 6 09 37 pm](https://user-images.githubusercontent.com/38869720/171124824-9e3fa95d-d1fb-4c4b-b9f6-bad70cb6c0fc.png)
**Figure: Social icons from SSW.Rules footer**

- There is a link to the home page https://codeauditor.com/ on the bottom of the home page
	- This should just scroll to the top instead of linking to itself
	- Maybe it should say "⬆️ Scroll to top"

### Tasks
- [x] Review suggestions
- [x] Implement if you agree

Thanks!

**Comment by jaydenalchin** [comment]
+1 to @bradystroud 's feedback above. 

Additional feedback: 

- The navbar is strange, logo and login/signup buttons should be at the top and other nav items should be below them. 
- The wrong logo is in use here, it should be the one shown here https://www.ssw.com.au/ssw/logo/CodeAuditor/

**Comment by tombui99** [comment]
Hey @bradystroud 
CC @jaydenalchin @adamcogan @tiagov8 

My apologies for the delay but I have made the following updates regarding UI feedback:

> Fix Menu Bar spacing 

Done

> Navbar logo and login/signup buttons should be at the top and other nav items should be below them

Done 

![image](https://user-images.githubusercontent.com/67776356/229393681-bd9a3161-1868-4537-b8f5-a53ece7eb359.png)

**Figure: Menu Bar spacing fixed and navbar repositioned**

> Displayed features on home page - These features should alternate which side the text is on

Done

![image](https://user-images.githubusercontent.com/67776356/229393776-e3901983-7cee-4cfd-8846-3f3b697c1981.png)

**Figure: features on homepage alternate side of text and image**

> Footer - Social icons should have all the same links as SSW Rules, People and Website

Done

![image](https://user-images.githubusercontent.com/67776356/229393917-d4752fb9-88cc-4c47-b52e-4c973d7c03cb.png)

**Figure: Social icons added to footer**

> Fix clunky instructions

Done - removed "About CodeAuditor" section and more/less buttons, and makes instruction clearer

![image](https://user-images.githubusercontent.com/67776356/229394206-230845e2-2f97-4bb2-9490-5d4281eb861e.png)

**Figure: Refined instructions**
