### ISSUE TITLE
🐛 Handling similar urls

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#347]
Cc: @adamcogan 

Hi @tombui99 

### Describe the Bug
These are the same page, but slightly different URLs
![image](https://user-images.githubusercontent.com/38869720/171126414-7344c6df-cb84-4329-8bcb-7fdc7759e3d9.png)

### Expected Behavior
Would be nice if CodeAuditor merged the scan histories for these links

### Tasks
- [ ] Investigate
- [ ] Fix

Thanks!

**Comment by tombui99** [comment]
Hi @bradystroud 
CC @adamcogan 

Closing this issue as it has been done in the newer issue requested by Tiago
See https://github.com/SSWConsulting/SSW.CodeAuditor/issues/419
