### ISSUE TITLE
✨UI/UX - HTML Rules - Error or Warning?

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#351]
@adamcogan 
Hi @tombui99 
  
### Pain
When configuring the enabled rules on a scan, I cant tell if the rules are errors or warnings

![Screen Shot 2022-06-09 at 11 13 40 am](https://user-images.githubusercontent.com/38869720/172743387-300f782d-a9d1-41f2-9b24-efe29ee6c325.png)
**Figure: can't tell type of rules**

### Suggested Solution
Show an icon next to each name to indicate type (error ⛔️, warning ⚠️)

### Tasks
- [x] Make the rule type clear to users

Thanks!

**Comment by tombui99** [comment]
Hi @bradystroud 
cc @adamcogan @william-liebenberg @tiagov8 

> Make the rule type clear to users

Done - I have added icon to show which rule is a warning or error

![image](https://user-images.githubusercontent.com/67776356/235603119-139871e5-8506-48f4-bd2f-0e7f0e6de13c.png)

**Figure: Added icon to show rule type**

I have also added the icons to the Rules page

![image](https://user-images.githubusercontent.com/67776356/235603618-e193f5a3-f044-4dba-8e53-5daf497484e9.png)
**Figure: Added icon in Rules page**

Please let me know if we need further design changes
