### ISSUE TITLE
♻️ Attributes - attribute names must be lowercase - fix false positives

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#352]
Cc: @adamcogan 

Hi @tombui99 

### Pain
This CodeAuditor rule [Attributes - attribute names must be lowercase](https://htmlhint.com/docs/user-guide/rules/attr-lowercase) is giving numerous errors.

I can't look at them all, but I noticed that it catches "viewBox" attributes for SVGs and it shouldn't (see https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox)

### What code could be improved?
CodeAuditor must not show errors for the attributes that can have an uppercase letter. 

Should report only the UPPERCASE  for the attributes on this list: https://www.w3schools.com/tags/ref_attributes.asp

### Tasks
- [ ] Investigate and fix

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan 

As per our conversation previously, we have agreed to disable this rule as it is causing a lot of false positives. Therefore, closing this issue
