### ISSUE TITLE
♻️ CodeAuditor rules titles - Improve prefixes and titles

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#353]
Hi @tombui99 and @adamcogan,

### Pain
We have a continuous problem with **overuse of prefixes** (I blame Adam for that 🤓)

From my understanding pretty much everything in CodeAuditor is related to HTML... so why some have HTML as prefix?!

### What code could be improved?

1. [Attributes - attribute names must be lowercase](https://htmlhint.com/docs/user-guide/rules/attr-lowercase) prefix seems unnecessary and inconsistent with others. I would change to "Attribute names must be lowercase"

2. [Links - href attribute must be either absolute or relative](https://htmlhint.com/docs/user-guide/rules/href-abs-or-rel). See the point above... why isn't this one also prefixed "Attribute"? It seems there is no standard or necessity... 
I would change to "The href must be either absolute or relative"

3. HTML / CSS and HTML/JS are inconsistent too. One has spaces before and after slash. The other doesn't. I would not have these prefixes, but if we are keeping them, then make consistent without spaces...

  <img width="434" alt="Screen Shot 2022-06-13 at 2 40 11 PM" src="https://user-images.githubusercontent.com/12601228/173450050-e7028d57-ee2e-4b38-9ccc-edd2ea6a5569.png">

4. [Figures - Do you use the right HTML/CSS code](https://www.ssw.com.au/rules/use-the-right-html-figure-caption) has a "Do you" which others don't. I would change it to "Use the right syntax for figures"

5. [URLs - must not include full stop or slash at the end](https://codeauditor.com/htmlhint/2707796e-dc8d-469c-7317-a71b7fa04f98?displayMode=0) has a prefix that reads with the rest... I would change it to "URLs must not include full stop or slash at the end"

### Tasks
- [ ] Check all the above with @adamcogan and fix the titles if he agrees

Thanks!

**Comment by tiagov8** [comment]
Hi @tombui99 

Is this task done and ready?

**Comment by tombui99** [comment]
Hi @tiagov8 

> Is this task done and ready?

Yes - This task has been completed and ready

![image](https://user-images.githubusercontent.com/67776356/188382935-8e375afc-8a40-4897-994d-f00242000afe.png)

**Figure: Updated rules titles**

**Comment by tiagov8** [comment]
Hey @tombui99 ,

See **RE: CodeAuditor - Rename custom rules' titles** I mentioned reordering ;)

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @adamcogan 

> As per our conversation, we need to group the rules with same prefixes

Done 

![image](https://user-images.githubusercontent.com/67776356/229014106-0cdf6ca3-098e-48b7-9e8d-802fb05070bf.png)

**Figure: same rule prefixes are grouped together**
