### ISSUE TITLE
🐛 We have a bunch of errors reported showing a 404 link

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#354]
Cc: @adamcogan 

Hi @tombui99 

### Describe the Bug
We have all these errors showing for a page that is actually a 404: https://www.ssw.com.au/rules/rules/report-bugs-and-suggestions (see double /rules/rules/)

<img width="1363" alt="Screen Shot 2022-06-13 at 2 58 42 PM" src="https://user-images.githubusercontent.com/12601228/173452387-402d9583-1065-4e1e-85ea-e7c0b4943407.png">

### Expected Behavior
I should only see **existing** pages on the reports.

PS. I agree we also need to check for our 404 page... so in that case, make CodeAuditor run on 1 clear page example. E.g. https://www.ssw.com.au/rules/404/

### Tasks
- [ ] Investigate
- [ ] Fix

Thanks!

**Comment by tombui99** [comment]
Hi Tiago, 

Done - I have fixed this so that we only scan html rules only for pages that returns HTTP 200 OK success status.

Please have a look at the latest scan here
https://codeauditor.com/build/c7f7ee1f-5d04-461e-205e-7072b9b4274a
