### ISSUE TITLE
🐛  Broken link false positives

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#364]
Hi @tombui99 

There are a false positives with the scan results for SSW.Rules
https://codeauditor.com/build/ebea3b88-b149-4f52-4f9a-af5c671be4fb

1. Anchor text `CRM Outlook Client Plugin`
1. Anchor text `pic.twitter.com/cr5n05FUn9`

False positives from a newer scan
https://codeauditor.com/build/ccf1adf8-cc1c-4721-6b47-940236903c64

3. http://www.salesforce.com/crm/

Thanks!

**Comment by tombui99** [comment]
Hi @bradystroud ,

Done - I have added the false positive links to the ignored list so it will not be reported 

See https://codeauditor.com/build/0ad46998-4038-400d-b5f9-69eae5726f2c
