### ISSUE TITLE
🐛 HTML rule configuration not saving  

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#366]
cc: @adamcogan 
Hi @tombui99,

The HTML rules configuration is not being saved.

Steps to reproduce:
1. Go to https://codeauditor.com/htmlhint/86467c8d-7f15-4e8f-8a13-a577912a328c
2. Click 'Enabled rules'
3. Change configuration (disabled a rule)
4. Click save
5. Refresh page
6. Click 'Enabled rules'
7. The configuration was not saved.

**Expected Behavior**
The configuration should be saved.

**Tasks**
- [ ] Investigate
- [ ] Fix

**More Information**
This issue wasn't previously happening, might be related to some recent changes?

Thanks!

**Comment by tombui99** [comment]
cc @adamcogan 
Hi @bradystroud,

> The configuration should be saved.

Done - As per our conversation, I have fixed it so now it is saving the configuration correctly

![image](https://user-images.githubusercontent.com/67776356/187825253-eb891c2c-27f6-49c9-b0f7-fe972292d54c.png)

**Figure: HTML rule configuration is now being saved correctly**
