### ISSUE TITLE
🐛 Bug - HTML rules not showing

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#375]
Cc: @william-liebenberg @adamcogan 

Hi @tombui99 

### Describe the Bug

<img width="960" alt="image" src="https://user-images.githubusercontent.com/38869720/189301664-84fec8cc-9095-4838-b475-15c9798ecdc1.png">

**Figure: Where are all the rules? 😱**

### To Reproduce
1. Go to https://codeauditor.com/htmlhint/04ed91d5-419d-4210-3bf0-b43617ab66e8
2. Click enabled rules 

### Expected Behavior
I can see all the rules

### Tasks
- [ ] Fix

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan 

Closing this issue as it has been done

![image](https://user-images.githubusercontent.com/67776356/228702770-9a7429da-2969-4b62-bbff-61587a752f20.png)

**Figure: Custom HTML rules modal is working as normal**

**Comment by tiagov8** [comment]
Hey @tombui99 

Did we ditch the "Enabled Rules" button? I couldn't find it in the lastest run: https://codeauditor.com/build/a012dfc3-bdda-4a45-eba5-03b34ea15c9a

<img width="1407" alt="Screenshot 2023-04-04 at 11 56 48 AM" src="https://user-images.githubusercontent.com/12601228/229833207-bdadbfa0-0507-45ce-a82c-b07e198d6743.png">
