### ISSUE TITLE
🐛 Working link showing as broken

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#397]
Cc: @adamcogan 

Hi @tombui99 

### Describe the Bug
Working link is showing as broken:

<div class="mb-3" style="box-sizing: border-box; border-width: 0px; border-style: solid; border-color: rgb(226, 232, 240); margin-bottom: 0.75rem; -webkit-font-smoothing: antialiased; color: rgb(51, 51, 51); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="font-bold mr-2" style="box-sizing: border-box; border-width: 0px; border-style: solid; border-color: rgb(226, 232, 240); font-weight: 700; margin-right: 0.5rem; -webkit-font-smoothing: antialiased;"><span> </span>Broken links on:</span><span> </span><a class="inline-block align-baseline link" target="_blank" href="https://www.ssw.com.au/rules/rules-to-better-research-and-development" style="box-sizing: border-box; border-width: 0px 0px 1px; border-style: solid solid dotted; border-color: rgb(226, 232, 240) rgb(226, 232, 240) rgb(158, 158, 158); text-decoration: inherit; background-color: transparent; color: inherit; display: inline-block; vertical-align: baseline; -webkit-font-smoothing: antialiased;">https://www.ssw.com.au/rules/rules-to-better-research-and-development</a></div>

Broken Link (1) | Anchor Text | Status | Message
-- | -- | -- | --
https://www.ato.gov.au/Business/Research-and-development-tax-incentive/ | ATO R&D Tax Incentive page | 404 | 404 Not Found

### To Reproduce
1. Go to https://codeauditor.com/build/5b918414-229e-4e3f-8835-445c58d35401
2. See last item - link is working

### Tasks
- [ ] Investigate
- [ ] Fix

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 ,
cc @adamcogan 

> Fix working link shown as broken

Done - Check scan https://codeauditor.com/build/46f4bdee-a65e-4a58-577b-f9e36e22dc0b

**Comment by tiagov8** [comment]
Hey @tombui99 

I'd love to have more context and understand what caused the bug and how it was fixed
