### ISSUE TITLE
🐛 Bug - Working link (with brackets) is being reported as broken

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#399]
Cc: @adamcogan 

Hi @tombui99  

### Describe the Bug

This link to Microsoft documentation https://learn.microsoft.com/en-us/previous-versions/sql/sql-server-2012/ee210549(v=sql.110)
... has brackets at the end

Those characters are transformed to code and it's showing as 404 on CodeAuditor:

<img width="1206" alt="Screen Shot 2022-12-19 at 4 04 56 PM" src="https://user-images.githubusercontent.com/12601228/208551571-47ddc810-5fc6-47ca-bd29-66cc2b2b1533.png">

### Tasks
- [x] Investigate
- [x] Fix

Thanks!

Related: #369 and #397

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan 

As per our conversation previously, this false positive report has been resolved and the link was added to the ignored link list. Therefore, I'm closing this issue

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan @william-liebenberg 

Closing as similar issue thread has been answered 

See https://github.com/SSWConsulting/SSW.CodeAuditor/issues/369
