### ISSUE TITLE
🐛 Profiles with no photo have a nice placeholder but still gives an error in CodeAuditor

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#400]
Cc: @adamcogan 

Hi @bradystroud / @tombui99 

### Describe the Bug

CodeAuditor is getting broken links for missing profile images, but in fact missing profile images have a working placeholder.

E.g.: https://www.ssw.com.au/rules/devops-master
shows https://github.com/SSWConsulting/SSW.People.Profiles/raw/main/David-Klein/Images/David-Klein-Profile.jpg

<img width="1193" alt="Screen Shot 2022-05-30 at 8 54 56 AM" src="https://user-images.githubusercontent.com/12601228/171027350-dc519b89-0803-44f0-b7fd-910eee899e03.png">

**Figure: CodeAuditor finds a broken link...**

<img width="579" alt="Screen Shot 2022-05-30 at 8 51 42 AM" src="https://user-images.githubusercontent.com/12601228/171026935-c9affdb2-2dc3-4d93-b4a2-7a87bb78ca91.png">

**Figure: Profiles with no photo have a nice placeholder but still gives an error in CodeAuditor**

### To Reproduce
1. Go to https://www.ssw.com.au/rules/devops-master
2. Scroll down to Acknowledgements section
3. See David Klein image is a placeholder (not broken)

### Expected Behavior
A profile with missing image shouldn't not generate a broken link.
E.g. CodeAuditor shouldn't get this URL https://github.com/SSWConsulting/SSW.People.Profiles/raw/main/David-Klein/Images/David-Klein-Profile.jpg

I believe the way the placeholder is inserted should REPLACE the potential URL for individual images, so the code doesn't have these broken links.

### Tasks
- [ ] Investigate
- [ ] Fix

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan @william-liebenberg 

> JK profile doesn't show his photo + gives an error in CodeAuditor

CodeAuditor is actually behaving correctly as the source of JK's profile picture (in GitHub) is missing.

When looking in the page source from https://ssw.com.au/rules/technical-debt/, the source of JK's image is pointed to this [GitHub URL](https://github.com/SSWConsulting/SSW.People.Profiles/raw/main/Jernej-Kavka-(JK)/Images/Jernej-Kavka-(JK)-Profile.jpg) which is a 404 page. Therefore, you would need to fix JK's GitHub profile page.
