### ISSUE TITLE
♻️ 🐛 Warning on 1:294 - don't know what is the error so can't fix

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#402]
Cc: @adamcogan 

Hi @tombui99 

### Pain
The warning for line 1:294 is being reported on pretty much every rule page.

Tip: See the very 1st warning on each page: https://codeauditor.com/htmlhint/d3ec0a53-e74f-408f-b203-ae7fca8a845e

It says "[Syntax - use the right HTML/CSS figure markup](https://www.ssw.com.au/rules/use-the-right-html-figure-caption)" but I don't see any figure on that line, and I am not sure what triggers CodeAuditor here... I assume this is a BUG 

### What code could be improved?
Please review the CodeAuditor rule parameters and what makes it give the warnings

### Tasks

- [ ] Investigate and fix so these warning are not shown on reports
- [ ] Before and after - Run a new report after done and let us know here how many less warnings we've got

<img width="612" alt="Screen Shot 2023-01-07 at 12 49 13 PM" src="https://user-images.githubusercontent.com/12601228/211169965-d680c891-4ae0-410f-8cba-e82ff600c7b8.png">

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @adamcogan 

This custom rule checks every "Figure" statements that it has to use the `<figcaption>` tag.
Please find following the good and bad examples that this custom rule is reporting:

Good example:
`<figcaption>Figure: Caption</figcaption>`

Bad examples:
`<dd>Figure: Caption</dd>`
`<p>Figure: Caption</p>`
`<strong>Figure: Track an Email in Outlook with Dynamics 365 App</strong>`
etc

**Comment by tiagov8** [comment]
Hey @tombui99 

> This custom rule checks every "Figure" statements that it has to use the <figcaption> tag.

I am aware of that. But note the problem here is that this is being shown on the very 1st line of code in hundreds of pages. It's not even in the content. I think it's reading a piece of <style> tag in the <head>

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @adamcogan @william-liebenberg 

> I think it's reading a piece of <style> tag in the <head>

You are correct, it was reading the `<style>` and report the error on the `<head>` - I have updated the custom rule so now it should not check for any `<style>` tag anymore.

I re-run the scan on SSW Rules and it no longer reports the error
