### ISSUE TITLE
🐛 "User name" grammar mistake is being reported as a Scrum term issue

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#404]
Cc: @adamcogan 

Hi @tombui99 

### Describe the Bug
See this warning from https://codeauditor.com/htmlhint/d3ec0a53-e74f-408f-b203-ae7fca8a845e 

It show as [Content - use the correct Scrum terms](https://www.ssw.com.au/rules/scrum-should-be-capitalized) but it seems like what it caught was the term "user name" with a space on it. This is not related to Scrum terms.

<img width="779" alt="Screen Shot 2023-01-07 at 1 28 07 PM" src="https://user-images.githubusercontent.com/12601228/211171001-f6f46bcc-8bcb-4468-9335-1d46ea98976f.png">
<img width="1266" alt="Screen Shot 2023-01-07 at 1 28 01 PM" src="https://user-images.githubusercontent.com/12601228/211171003-cc119318-9610-4d4e-948a-f7c035f16ceb.png">

### Expected Behavior
This should be pointed as a grammar mistake, but not a "Scrum term" mistake

### Tasks
- [x] Investigate
- [x] Fix

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @adamcogan 

> "user name" should be pointed as a grammar mistake, but not a "Scrum term" mistake

Done - I have removed "user name" from the list of terms to be checked by the rule

![image](https://user-images.githubusercontent.com/67776356/213093851-05a6de0f-0205-480c-9d81-f128a0803eb7.png)
**Figure: "user name" removed from check list**

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan 

Closing as issue has been resolved
