### ISSUE TITLE
♻️ Syntax - YouTube videos must not be under an embed URL... Reason links are not clickable

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#406]
Cc: @adamcogan 

Hi @tombui99 

### Pain
I am looking at a report on By Reason view.

I saw this [Syntax - YouTube videos must not be under an embed URL](https://codeauditor.com/htmlhint/d3ec0a53-e74f-408f-b203-ae7fca8a845e?displayMode=1)
I want to know more about it, so I clicked the link (underlined text) 
NOTHING happens...

<img width="1321" alt="Screenshot 2023-01-15 at 1 31 39 PM" src="https://user-images.githubusercontent.com/12601228/212568487-5fd43e7a-8207-4309-bbd7-c6b2ee5a222e.png">

### What code could be improved?
I want to be able to know more about what each CodeAuditor rule says by clicking on them.

### EXTRA (⚠️ important)
When I clicked on the code line I see NOTHING that is related to a YouTube video... so I think this rule is broken!

<img width="1163" alt="Screenshot 2023-01-15 at 1 35 34 PM" src="https://user-images.githubusercontent.com/12601228/212568561-f3a433cb-f6b0-425c-bb7a-98b67e0f3763.png">

### Tasks

- [ ] Make reason links work
- [ ] Investigate and fix the reports so user can see the problem

Thanks!

**Comment by tiagov8** [comment]
Note: I tested the "embed" vs "watch" links and the difference is the 1st open in full screen, the 2nd in the YouTube site (with other videos around, menu, etc)

**Comment by tombui99** [comment]
Hi @tiagov8 

> Note: I tested the "embed" vs "watch" links and the difference is the 1st open in full screen, the 2nd in the YouTube site (with other videos around, menu, etc)

Yes that's correct. The rule is checking that all youtube links must have "embed" in it.

Let me know if we should keep or disable this rule.

**Comment by tiagov8** [comment]
Hi @tombui99 

I guess we should just disable it then

1. Please action

**Comment by tombui99** [comment]
Hi @tiagov8 

> Disable the rule

Done - I have disabled the rule for future scans
