### ISSUE TITLE
✨ See numbers of warnings/errors when filter "by Reason"

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#410]
CC: @adamcogan 

Hi @tombui99 
  
### Pain
When I look at "by Reason" view https://codeauditor.com/htmlhint/1fbff3e7-9552-4f0e-329c-a22bf05a8a54?displayMode=1
I'd like to know how many warnings/errors we have for each of the reasons...
<img width="978" alt="Screenshot 2023-02-04 at 1 09 48 PM" src="https://user-images.githubusercontent.com/12601228/216789744-c73bbd96-7b22-496f-972d-2cefe0473c0a.png">

### Suggested Solution
Show the number of warning per reason... E.g:
<img width="708" alt="Screenshot 2023-02-04 at 1 14 31 PM" src="https://user-images.githubusercontent.com/12601228/216789853-fd3b85f6-d665-47f7-b77f-e916cb6969cc.png">

### Tasks

- [x] Implement count for warnings/errors on each reason line
 

Thanks!

**Comment by tiagov8** [comment]
Update: Change the emojis with the same icons as https://github.com/SSWConsulting/SSW.CodeAuditor/issues/411

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan 

> Implement count for warnings/errors on each reason line and update emojis

Done 

![image](https://user-images.githubusercontent.com/67776356/228700772-ab5bc003-4877-4c52-aa54-ba9ff4ff9ba3.png)

**Figure: Reason line with warning/errors with updated emojis**

**Comment by tombui99** [comment]
Hi @tiagov8
CC @adamcogan

Closing this issue as it has been done

**Comment by tiagov8** [comment]
cc @jaydenalchin 

Thanks @tombui99 

Because the numbers are so different, I would add them at the end instead, so the alignment/readability is better.

E.g.:
from

>  **(765)** Syntax - code blocks must have a language 
>  **(32357)**  Content - use the correct Scrum terms) 
>  **(202)** Content - Use Unicode Hex code for special HTML characters 
>  **(9)** Tags - id and class must not use the 'ad' keyword 

to 

>  Syntax - code blocks must have a language **(765)**
>  Content - use the correct Scrum terms) **(32357)**
>  Content - Use Unicode Hex code for special HTML characters **(202)**
>  Tags - id and class must not use the 'ad' keyword **(9)**

1. Please action

**Comment by tombui99** [comment]
Hi @tiagov8 

> Please action

Done - I have fixed the alignment so the numbers are on the right

![image](https://user-images.githubusercontent.com/67776356/232688417-a0239191-b1b8-4d48-ac76-258a2bed7973.png)

**Figure: updated alignment for number of warnings/errors**
