### ISSUE TITLE
♻️ UI/UX - Unnecessary info icon that only shows an emoji 🤨

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#411]
Cc: @adamcogan

Hi @tombui99 

### Pain
We have an "info" icon that just show emojis...

<img width="655" alt="Screenshot 2023-02-04 at 1 16 32 PM" src="https://user-images.githubusercontent.com/12601228/216789961-3107c259-1caa-444f-8885-591764633c45.png">

Also...the emojis are not the most accurate...

 😵 for warning and 😡 for error

### What code could be improved?
1. Can we skip the "info" icon...
2. And just have the emoji next to the text?  
   I would use ❗️ for warning;
   and ⛔️ for error

### Tasks

- [x] Improve the UI/UX. E.g.
<img width="669" alt="Screenshot 2023-02-04 at 1 24 15 PM" src="https://user-images.githubusercontent.com/12601228/216790153-6e277749-9e5e-406e-9ea6-0a4907ff872e.png">

Thanks!

**Comment by tiagov8** [comment]
@jaydenalchin Can we have your thoughts on this one?

**Comment by jaydenalchin** [comment]
> @jaydenalchin Can we have your thoughts on this one?

The current state is definitely carrying a lot of redundancy, and the above solution is good but I have issues with using emojis in UI like this as we have less control over how they appear system to system and they can vary widely.

The core of what we're trying to do here is emphasise the warnings and errors so:

1.  Replace the info icons with separate warning & error icons respectively 
2. Colour the icons as appropriate (yellow for warning, red for error)
3. Consider colouring the warning text yellow too (as shown below) for internal consistency as well as consistency with common material design standards as well.
4. Less important, but visually center the text/labels if possible.

![image](https://user-images.githubusercontent.com/75593567/216850598-90216c4f-750a-4caa-9094-790cd0ed545a.png)
**Figure: Highlighting warnings vs errors**

**Comment by tiagov8** [comment]
That's way better!

@tombui99 

1. Can you implement JD's solution? (let me know if you need help with the image or CSS)

**Comment by tombui99** [comment]
Hi @tiagov8 and @jaydenalchin 
cc @adamcogan 

> Can you implement JD's solution?

Done - I couldn't find the hexagon warning icon so I just use the same one with different color instead. Let me know if these icon needs changes

![image](https://user-images.githubusercontent.com/67776356/217668615-b478b512-0b95-4b1c-b62e-bc050a5f15d3.png)

**Figure: New icons for info number**

**Comment by tiagov8** [comment]
Hey @tombui99 

1. See if you can use the free icons from FontAwesome (SVG code is preferred)
* **Warning** - https://fontawesome.com/icons/triangle-exclamation?s=solid&f=classic
* **Error** - https://fontawesome.com/icons/circle-exclamation?s=solid&f=classic

2. Can you also add the error icon to the LINKS section beside "404 Errors"

**Comment by tiagov8** [comment]
Test pass ✅

Please let us know when it's live in prod

**Comment by tombui99** [comment]
Thanks @tiagov8 

It is live now - Please also make sure to clear your browser's cache if you don't see the new updates
https://codeauditor.com/build/1fbff3e7-9552-4f0e-329c-a22bf05a8a54

**Comment by tombui99** [comment]
Hi @tiagov8
CC @adamcogan

Closing this issue as it has been done
