### ISSUE TITLE
🐛 'Replace' misspelled on homepage

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.CodeAuditor#413]
### Describe the Bug
Home page should say 'replace' instead of 'repace'

### To Reproduce
1. Go to https://codeauditor.com/
3. Scroll down to 'Instructions to scan an URL'
4. See typo

### Expected Behavior
Home page should say 'replace' instead of 'repace'

### Tasks
- [ ] Fix spelling mistake

### Screenshots
![image](https://user-images.githubusercontent.com/2636640/219985179-5e5f18ab-5a22-4117-891e-76609574bdcc.png)

Thanks!

**Comment by tombui99** [comment]
Hi @danielmackay 

> Fix spelling mistake

Done - As per our conversation, I have fixed the spelling mistake

![image](https://user-images.githubusercontent.com/67776356/225461453-e78045d7-30e1-45ed-b671-a3947975b980.png)

**Figure: Corrected spelling mistake**

**Comment by danielmackay** [comment]
Thanks @tombui99. 🙂
