### ISSUE TITLE
✨ Add support to run via Edge

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.CodeAuditor#414]
### Pain
I would like

### Suggested Solution
Currently Chrome needs to be installed in order for the docker image to successfully run.  Should allow for Edge to also be used as it is a Chromium based browser

### Tasks
- [ ] Add support for Edge

### Screenshots
![image](https://user-images.githubusercontent.com/2636640/219985865-3f5bbefc-8198-4042-885d-bf138cbab1ad.png)

Thanks!

**Comment by tombui99** [comment]
Hi @danielmackay 
CC @adamcogan 

Closing this issue as chrome no longer supports dependancy in Docker, thus running via Edge is not possible
