### ISSUE TITLE
✨ Add Chrome dependency into the container

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.CodeAuditor#415]
### Pain
Currently the docker image will not run without Chrome being installed.  

### Suggested Solution
This should be baked into the container so that all required dependencies are contained within the image.

### Tasks
- [ ] Add Chrome into the docker image

Thanks!

**Comment by danielmackay** [comment]
Hey @tombui99 .  Happy for you to close this issue if chrome is no longer a dependency in the tool.

**Comment by tombui99** [comment]
Hi @danielmackay 
CC @adamcogan 

Closing this issue as chrome no longer supports dependancy in Docker
