### ISSUE TITLE
♻️ SSW.Rules - Can't fix "Syntax - script tags cannot be used inside another tag"

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#416]
Cc: @bradystroud 

Hi @tombui99 

### Pain
CodeAuditor caught **2535** "Syntax - script tags cannot be used inside another tag" errors on SSW.Rules

All these errors are actually the same 3 errors on many pages. They are on the header in the master page.

As far as I'm concern there is NOTHING to be fixed... since the `<script>` tags are inside `<head>` which is where it should be

<img width="1350" alt="Screenshot 2023-03-10 at 5 36 09 PM" src="https://user-images.githubusercontent.com/12601228/224423678-549c9132-2c04-460c-9fcd-c28769ca7682.png">

**Figure: See EVERY error is the same lines on every page**

### Tasks

- [x] Investigate and fix 
    Either CodeAuditor reports @tombui99 
    OR 
    SSW.Rules head code @bradystroud 

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @bradystroud 

> As far as I'm concern there is NOTHING to be fixed... since the <script> tags are inside <head> which is where it should be

I do agree that this is a hard fix. However, this HTML rule is the default one that comes with the library (See https://htmlhint.com/docs/user-guide/rules/head-script-disabled), I can simply disable and ignore it if you would like.

**Comment by tombui99** [comment]
Closing as we decided
