### ISSUE TITLE
♻️ SSW.Rules - Can't fix "URLs - Detect absolute references path correctly" 

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#417]
Cc: @bradystroud 

Hi @tombui99 

### Pain
CodeAuditor caught **861** "URLs - Detect absolute references path correctly" errors on SSW.Rules

All these errors are actually the same error on many pages. Seems like the error is on the **breadcrumb / title / edit** area.

I am not sure WHY it returned "only" 861 errors... knowing that area is in EVERY page...

Also... It seems like most of the results are in **Rules categories** (e.g. https://ssw.com.au/rules/rules-to-better-marketing/) but some are in **Individual Rules** (E.g. https://ssw.com.au/rules/registration/)

<img width="1392" alt="Screenshot 2023-03-10 at 5 43 31 PM" src="https://user-images.githubusercontent.com/12601228/224424721-8fac2498-425b-430c-939d-f845f06ed739.png">

**Figure: See EVERY error is the same line on every page**

---

**Exception:** This is a page where this error appeared in a different location of the code (although nothing looks wrong with it)
https://ssw.com.au/rules/rules-to-better-business-intelligence/

<img width="1284" alt="Screenshot 2023-03-10 at 5 56 44 PM" src="https://user-images.githubusercontent.com/12601228/224426893-b9a043e1-6a04-42d4-8147-4a235fd9aae9.png">

---

### Tasks

- [x] Investigate and fix 

Thanks!

**Note:** Related to Issue #416

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @bradystroud 

> All these errors are actually the same error on many pages. Seems like the error is on the breadcrumb / title / edit area

The errors reported are actually expected according to the custom rule's logic. The href from SSW Rules url should point to a path. Please see:

**Bad Example:**
`<a href="https://ssw.com.au/rules/when-you-use-mentions-in-a-pbi/" />
`

**Good Example:**
`<a href="/rules/when-you-use-mentions-in-a-pbi/" />
`

**Comment by tiagov8** [comment]
Hey @bradystroud 

1. Please update the breadcrumb link "SSW Rules" to be relative instead of absolute

From

   `https://ssw.com.au/rules`

to

  `/rules`

**Comment by tombui99** [comment]
Hi @tiagov8 

> I assume the above will reduce the number of warnings drastically, correct?

Yes - that will fix it and no more warnings should be reported

> Could you change the warning title to "URLs - Detect absolute internal links"

Done - custom rule title changed

![image](https://user-images.githubusercontent.com/67776356/227100454-904b692f-5dbb-4a5f-9b21-af58345e2f32.png)

**Figure: New custom rule title**

**Comment by tiagov8** [comment]
Hey @bradystroud 

I added an Issue on SSW.Rules to fix this: https://github.com/SSWConsulting/SSW.Rules/issues/939 

If you find convinient, please close this one ;)
