### ISSUE TITLE
♻️ UI - Improve breadcrumb + last scanned info at the top

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#422]
Cc: @adamcogan 

Hi @tombui99 

### Pain
Not a big fan of the info in this area:

<img width="1095" alt="Screenshot 2023-04-03 at 9 33 24 PM" src="https://user-images.githubusercontent.com/12601228/229656110-62e90296-59cd-419c-88cf-a4b07a35fbf4.png">

### What code could be improved?
Better information

#### 1. BREADCRUMB
- [ ] Add a Home at the beginning (of course add the link)
- [ ] Change from "Builds" to "Scans" + update the link to go to https://codeauditor.com/explore
- [ ] Change from "a012dfc3-bdda-4a45-eba5-03b34ea15c9a > Links" to "Scan Results"

It should change from
`Builds >  a012dfc3-bdda-4a45-eba5-03b34ea15c9a > Links`
to
`Home > Scans > Scan Results`

#### 2. SCAN INFO
- [ ] Move the date to be together with the "X days ago at Y" (keep the date bold, but in the same font size as the rest)
- [ ] Remove the dot after "p.m."

It should change from:
```
https://www.ssw.com.au/rules/
Last scanned: 3 days ago at 11:25p.m.
Duration: 1m 52s
31 Mar 2023
```
    
to:    
 ```
https://www.ssw.com.au/rules/
Last scanned: 31 Mar 2023 (3 days ago at 11:25p.m)
Duration: 1m 52s
```

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan @william-liebenberg 

> 1. BREADCRUMB
 Add a Home at the beginning (of course add the link)
 Change from "Builds" to "Scans" + update the link to go to https://codeauditor.com/explore
 Change from "a012dfc3-bdda-4a45-eba5-03b34ea15c9a > Links" to "Scan Results"

> 2. SCAN INFO
 Move the date to be together with the "X days ago at Y" (keep the date bold, but in the same font size as the rest)
 Remove the dot after "p.m."

All done - I have fixed the UI for breadcrumb area as requested

![image](https://user-images.githubusercontent.com/67776356/232412979-52b303d9-0409-48ed-9d36-55cce9ae58ea.png)

**Figure: Fixed UI for breadcrumb area**
