### ISSUE TITLE
♻️ UX/UI - Change "Cancel" button to "X Close" + remove duplicate

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#424]
Cc: @adamcogan 

Hi @tombui99 

### Pain
When you open the lightbox to see where in the code the errors are, there is a "Cancel" button. This label is missleading since no action was requested. It should read "Close"

Also, there is a X at the top right which does the very same thing

### Tasks
- [ ] Change "Cancel" button to "X Close" 
- [ ] remove duplicate "X"

<img width="1324" alt="Screenshot 2023-04-05 at 10 53 16 AM" src="https://user-images.githubusercontent.com/12601228/230102920-684183a7-a348-470b-ac5f-282b4143aed0.png">

Thanks!

**Comment by tiagov8** [comment]
Hey @jaydenalchin please comment if you have a better idea

**Comment by jaydenalchin** [comment]
> Hey @jaydenalchin please comment if you have a better idea

+1 - Though I don't think the button needs the x in it. 

Note: the lightbox should also close if the user clicks outside of it.

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @jaydenalchin @adamcogan @william-liebenberg 

> Remove duplicate "X"
 Change "Cancel" button to "Close"
The modal should also close if the user clicks outside of it

All done - I have removed duplicated "X", changed from "Cancel" to "Close" and close the modal if click outside

![image](https://user-images.githubusercontent.com/67776356/232405184-13db945b-b629-4380-988d-da769038b631.png)


**Figure: Fixed UI for modal**
