### ISSUE TITLE
👷 DevOps - Add scheduled weekly scan for SSW Rules, Websites and People

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#427]
Cc: @adamcogan @william-liebenberg 

Hi @tiagov8 
  
### Pain

As per my conversation with Tiago, we should add weekly scheduled CodeAuditor scan for SSW Rules, People and Website build pipeline.

### Tasks

- [ ] Fix SSW Rules scheduled scan from 2 weeks to every week
- [ ] Add scheduled scan every week for People and Website

Thanks!

**Comment by tiagov8** [comment]
Hey @tombui99 

Can you make Website on Mondays, People on Wednesdays, and Rules on Fridays?

I think it will help us having constant new reports to look at

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan @william-liebenberg 

> Can you make Website on Mondays, People on Wednesdays, and Rules on Fridays

Done - I have rescheduled the automated scans to be as follow:

1. SSW Website - scan at 1pm every Monday
See https://github.com/SSWConsulting/SSW.CodeAuditor/blob/main/.github/workflows/ssw-website-scan.yml

2. SSW People - scan at 1pm every Wednesday
See https://github.com/SSWConsulting/SSW.CodeAuditor/blob/main/.github/workflows/ssw-people-scan.yml

3. SSW Rule - scan at 1pm every Friday
See https://github.com/SSWConsulting/SSW.CodeAuditor/blob/main/.github/workflows/ssw-rules-scan.yml

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @william-liebenberg @adamcogan @wicksipedia @christianmorfordwaitessw 

As per my conversation with Brady, Matt and Christian, I have incorporated the CodeAuditor scan into SSW Rules, People, and Website, and arranged for weekly execution. The schedule is as follows:

SSW Website - scan at 1pm every Monday
See https://github.com/SSWConsulting/SSW.Website-v3/blob/main/.github/workflows/weekly-codeauditor-scan.yml

SSW People - scan at 1pm every Wednesday
See https://github.com/SSWConsulting/SSW.People/blob/main/.github/workflows/ssw-people-scan.yml

SSW Rule - scan at 1pm every Friday
See https://github.com/SSWConsulting/SSW.Rules/blob/main/.github/workflows/codeauditor-test.yml
