### ISSUE TITLE
🐛 BUG - Can't view source 

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#439]
Cc: @adamcogan 

Hi @tombui99 

### Describe the Bug
When I look at some report (filtered "by reason") e.g. https://codeauditor.com/htmlhint/0cac0b88-56c5-4aed-5a1a-708a96feaf71 

I can't see any source! It just shows "Internal error"

### To Reproduce
1. Go to Reports
2. Find an issue location
3. Click on the line
4. See the error

### Expected Behavior
See the source code with the error highlighted

### Tasks
- [x] Investigate
- [x] Fix

### Screenshots

<img width="862" alt="Screenshot 2023-05-05 at 3 44 45 PM" src="https://user-images.githubusercontent.com/12601228/236543065-fb1595a9-3d17-4c59-8b30-fff0599b22ed.png">

<img width="854" alt="Screenshot 2023-05-05 at 3 44 39 PM" src="https://user-images.githubusercontent.com/12601228/236543058-82484a57-2971-4f6f-b3ae-a425ca8cf32a.png">

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 

> Investigate and Fix

Done - I have refreshed our Firebase function api and now it is back to work

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/a7756b93-29be-4a6a-ac8a-7802b8c232c4)

**Figure: View source window back to work**
