### ISSUE TITLE
Add --private flag when running scan

### ISSUE THREAD

**Issue by nvhoanganh** [SSWConsulting/SSW.CodeAuditor#44]
By default when running scan, scan results will be "public" and will be visible to unauthenticated users under https://codeauditor.com/publicscans. if user doesn't want this, they need to supply --private flag.

To do:
- update the README which appears in home page and explain the above. (e.g. your scan is public unless you supply --private flag)
- update the docker accordingly
- the scans table will now have this flag which we can use to show public scans to unauthenticated users

**Comment by tombui99** [comment]
Done - Private flag added when running scan to allow user upload scan privately
