### ISSUE TITLE
✨ Spaces needed after emojis 

### ISSUE THREAD

**Issue by jontygardner** [SSWConsulting/SSW.CodeAuditor#443]
Hey @tiagov8 
CC: @adamcogan @pierssinclairssw @william-liebenberg 
https://www.ssw.com.au/rules/document-discoveries/ 

❌ There should be a space after the emojis

1.	Do we have a rule on this?
2.	Please fix it. 

Hi @tombui99 

1.	Please make a code auditor rule for this 
2.	Run it on SSW Rules and see how many exceptions it finds 
 
![image](https://user-images.githubusercontent.com/97415708/236770300-912271c1-82f1-4744-8147-c25bdd3f3885.png)
Figure: Should be a space after the emojis 

Thanks!
Jonty

**Comment by tiagov8** [comment]
> 1. Do we have a rule on this?
It’s a tip under https://ssw.com.au/rules/use-emojis/
 
   > 2. Please fix it.
Not done – there is nothing to fix. 
 
What you see there is **not** an emoji, but the icon used as captions as per https://ssw.com.au/rules/rule/#7-captions
