### ISSUE TITLE
✨ Latest scan route

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#444]
Cc: @adamcogan @william-liebenberg 

Hi @tombui99 

It would be awesome if we could have a link to the latest scan for a specific site.
e.g. codeauditor.com/ssw-website/latest

```[tasklist]
### Tasks
- [x] Add route
```

Thanks!

**Comment by tombui99** [comment]
cc @adamcogan @william-liebenberg 

Hey @bradystroud 

> Add route to latest scan for a specific site

Done - I have added a new route that lets you go to the latest scan on a site

The route is as follow:

`https://codeauditor.com/latest/{your personal token}/{site url}`

Here is an example:

`https://codeauditor.com/latest/02ad5e57-04e6-4c4f-bdd4-1e62d495e6d5/ssw.com.au%2Frules`

Note: The special characters (if any) in your Url param must be encoded, I'd recommend using https://www.urlencoder.org/ when encoding your Url. Also don't include `https` or `www`.

Let me know if there's anything!

Thanks!
