### ISSUE TITLE
♻️ Firebase - Review billing configuration and ownership

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#447]
Hi @william-liebenberg 
cc @adamcogan 

As per my conversation with @william-liebenberg , we need to review the billing configuration on Firebase to SSW accounts

- [x] Review and adjust billing configuration on Firebase

**Comment by tombui99** [comment]
cc @adamcogan @william-liebenberg 

> Review and adjust billing configuration on Firebase

Done - I have reviewed and added @william-liebenberg as co-owner of the project

**Comment by william-liebenberg** [comment]
Hi @tombui99 

Have you removed old ex-ssw members?

**Comment by tombui99** [comment]
Reopened as Anthony is still reviewing on fixing the billing account

**Comment by tombui99** [comment]
cc @adamcogan @william-liebenberg 

> Remove ex-ssw members from current project

Done - I have removed ex-ssw members and I have also worked with @leahy268 to reconfigure the billing for both staging and production of CodeAuditor
