### ISSUE TITLE
🐛 Network Error on Firefox

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.CodeAuditor#454]
Cc: @bradystroud 

Hi Team,

### Describe the Bug

When attempting to load the following page on Firefox, I get a network response error: https://codeauditor.com/htmlhint/6d8d72b4-2271-4098-a12e-0d67699d3078

![Network Response](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/25432120/65f07d77-27c1-45e9-920c-6174f01ff9df)

### To Reproduce
1. Go to https://codeauditor.com/htmlhint/6d8d72b4-2271-4098-a12e-0d67699d3078 on Firefox

### Expected Behavior

There should be no errors and should load the content correctly

### Tasks
- [ ] Investigate
- [ ] Fix

### Environment
 - Device: M1 Macbook
 - Browser: Firefox
 - OS: MacOS

Thanks!

**Comment by tombui99** [comment]
Hi @BrookJeynes 
cc @bradystroud @william-liebenberg @adamcogan 

> Investigate Network error on Firefox

I tried running CodeAuditor on Firefox and it is working just fine. I'm also on the exact same environment as you (M1 Macbook).

It seems to be the `Enhanced Tracking Protection` setting in Firefox that caused the error - I would recommend either use its 'Standard' option or turn it off.

See Firefox documentation for configuration: https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop.

Let me know if you still have this issue
