### ISSUE TITLE
🐛 Run on SSW.Website - Source and destination are the same - How to fix?

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#483]
Cc: @adamcogan 

Hi @tombui99 

### Describe the Bug
[This week's 1 broken link on SSW.Website run](https://codeauditor.com/build/bc02f0b7-88de-4f81-092b-d1afca850713?displayMode=2) has the same link as source and destination:
https://www.ssw.com.au/ssw/Standards/Rules/RulestoBetterDeadTime.aspx

I can't fix it!

**Note:** The content from this old page has been moved to a draft post on Adam's blog: https://adamcogan.com/?p=3510 (needs authentication to see it)

### Expected Behavior
The source link should always be a live page

### Tasks
- [ ] Investigate
- [ ] Fix
- [ ] Inform here what caused this

<img width="1355" alt="Screenshot 2023-06-02 at 12 55 44 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/5fc2a1ed-b7fc-48b0-b607-d96440904be9">

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @william-liebenberg 

> The source link should always be a live page

After investigating the link scanning tool, I believe the page must still exist somewhere on the live page that CodeAuditor was still able to find it.

1. Can you help check if the page has been completed removed from the live one

**Comment by tiagov8** [comment]
Hi @tombui99 

I don't see the page here: https://ssw2.visualstudio.com/SSW.Website/_versionControl?path=%24/SSW.Website/trunk/SSW.Website.WebUI/Standards/Rules&version=T

<img width="1595" alt="Screenshot 2023-06-21 at 9 06 12 AM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/5e099c2f-e9c1-4c8e-919e-dce13486578b">

**Comment by tombui99** [comment]
Hey @tiagov8 

I found some more similar broken links to the one that you found. However, these are not the same links - the source link is "https" while the broken destination link is "http" without security protocol

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/45e601b9-8a32-4f95-bc4a-33647712ef38)

Do you know what could the reason be?

**Comment by tiagov8** [comment]
Hey @tombui99 

> Do you know what could the reason be?

I don't know for sure :/
But since you noticed the protocol change, maybe it's due to Server redirects... 

1. Please send an email to SysAdmins asking if they know more about this?

**Comment by tombui99** [comment]
As discussed with @william-liebenberg , we need to check with Website teams the static content in CRM and SharePoint and any other possible sources.

**Comment by tombui99** [comment]
cc @bradystroud @william-liebenberg @adamcogan 

I have added a new issue on SSW Website to look into this issue
See https://github.com/SSWConsulting/SSW.Website/issues/1089
