### ISSUE TITLE
♻️ Allow emails if they are inside code tags

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#484]
Cc: @adamcogan 

Hi @tombui99 

### Pain
We have a rule on not displaying emails in content, which is fair. 

[Content - Text must not display any email addresses](https://www.ssw.com.au/rules/avoid-clear-text-email-addresses-in-web-pages)

However we do need to use examples sometimes (e.g. all@northwind.com) + there are scenarios when this is not an issue (e.g. 2weeks@followupthen.com)

In those cases, we have added the email address in code (e.g. `all@northwind.com`)

### What code could be improved?
CodeAuditor rule should NOT catch email addresses if they are inside a code tag.

The examples are in the latest report https://codeauditor.com/htmlhint/cac77a63-5b0f-4273-a984-0e9bf1d117ef?displayMode=1

<img width="1174" alt="Screenshot 2023-06-02 at 6 12 12 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/3cdd2dc8-f265-423f-8aa0-0d161b01b4cf">

### Tasks
- [x] Confirm with another dev if this is a good idea
- [x] Make CA ignore email addresses that are inside code

Thanks!

**Comment by tombui99** [comment]
Hey @tiagov8 

> Confirm with another dev if this is a good idea

Done - As per my conversation with @william-liebenberg , we agreed that we should ignore email addresses if they are inside code tags

> Make CA ignore email addresses that are inside code

Done - I have updated the custom rule so in future scans it will ignore email addresses that are inside code tags
