### ISSUE TITLE
♻️ UI - Differentiate 404 and Error icons on CodeAuditor

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#487]
Cc: @BrookJeynes @bradystroud 

Hi @jaydenalchin @tiagov8 @hveraus 

### Pain

Currently the errors and 404 errors have the same icon. As per my conversation with [@BrookJeynes](https://github.com/BrookJeynes) we will be changing the 404 errors icon to something else

<img width="316" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/b63e023b-97e3-485b-b5a1-7f0e465fd32a">

**Figure: Current icons used in CodeAuditor**

### Tasks

- [ ] Provide feedback and see if we should replace these icons

Thanks!

**Comment by tiagov8** [comment]
Hey @tombui99 @BrookJeynes 

What about https://fontawesome.com/icons/link-slash?f=classic&s=solid ?

**Comment by tombui99** [comment]
Hey @tiagov8 
cc @BrookJeynes 

> What about https://fontawesome.com/icons/link-slash?f=classic&s=solid 

This icon looks awesome! I have replaced all the old ones with this new one!

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/4d403de6-d40f-49cb-b610-e17bb12b231d)

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/c4ec5506-911e-4702-bcd4-a39527194006)

**Figures: New 404 errors icons**
