### ISSUE TITLE
📝 How it Works - "What is" section content improvements

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#489]
Cc: @adamcogan 

Hi @tombui99 

### Tasks

On https://codeauditor.com/howitworks 

- [ ] Change from

> What is CodeAuditor?
> CodeAuditor is a tool that automatically scans your website and its code to check
> 
> Broken Links - links to pages which do not work
> HTML Formatting - which may cause pages to be incorrectly shown to the user.
> Lighthouse Scan - audits for performance, accessibility, SEO and more
> Artillary Load Test - load tested to see how it behaves when there are a lot of users accessing it at once

to

> What is CodeAuditor?
> CodeAuditor is a tool that automatically scans your website and its code to:
> 
> * **Find broken Links** - Links to pages which do not work
> * **Check HTML formatting** - May cause pages to be incorrectly shown to the user
> * **Lighthouse scan** - Audits for performance, accessibility, SEO, and more
> * **Artillery load test** - See how website behaves when lot of users access it simultaneously 

PS. Sorry couldn't follow https://ssw.com.au/rules/change-from-x-to-y here in GitHub

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @william-liebenberg 

> Change to
What is CodeAuditor?
CodeAuditor is a tool that automatically scans your website and its code to:
Find broken Links - Links to pages which do not work
Check HTML formatting - May cause pages to be incorrectly shown to the user
Lighthouse scan - Audits for performance, accessibility, SEO, and more
Artillery load test - See how website behaves when lot of users access it simultaneously


All done - I have updated the page as follow

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/d24bada6-015c-4cff-8794-4a67451e7f3e)

**Figure: Modified "How it works" page**
