### ISSUE TITLE
✨ UI - Create an Error page

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#493]
cc @william-liebenberg @tiagov8 @adamcogan 

CodeAuditor should have an error page when an Url is invalid

- [ ] Create an error page for CodeAuditor

**Comment by tombui99** [comment]
cc @william-liebenberg  @tiagov8 @adamcogan 

> Create an error page for CodeAuditor

Done - I have created an error page for CodeAuditor to redirect invalid urls

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/d9024c41-5710-436a-8bf8-08b608d32db0)

**Figure: CodeAuditor error page**

Hi @tiagov8 

Please let me know if you have any UI feedback regarding this page

**Comment by tiagov8** [comment]
1. Change from

    **404
    Oops!** Page not found
    
    To
    
    Ooops!
    **404 - Page not found**
    
    Note: Bold = **red**

2. Make sure the red is `#CC4141` as per SSW colors

3. Make sure the button has an hover effect 

4. Make the "Go home" text white

(more on https://www.ssw.com.au/ssw/company/Web-Reference.aspx#Buttons)

5. Change from
"Go home"
to
"Go to the homepage"

6. Change from
"The page you're looking for doesn't exist"
to
"We're sorry, but it seems like the code is playing hide-and-seek with this page."

**Comment by tombui99** [comment]
Hi @tiagov8 

Thanks for your feedback

All done - Let me know if this UI needs further improvement

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/aa2fe4bd-1ce7-4dcd-9ac5-66540d1bea1e)

**Figure: Error page with modified UI**

**Comment by tiagov8** [comment]
@tombui99 
Is the text "404 - Page..." in SSW red?

**Comment by tombui99** [comment]
Hey @tiagov8 

> s the text "404 - Page..." in SSW red?

Yes it is

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/7dc35fd5-a1c3-4c0b-9a84-ce21deab11a9)
