### ISSUE TITLE
♻️ UI - Improvements to "Compare" and "Email Alerts" new features

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#494]
Cc: @jaydenalchin @william-liebenberg @bradystroud @BrookJeynes @hveraus 

Hi @tombui99 

As per our Teams group conversation:

> Hey Tiago Araujo [SSW], I have made some UI improvement from your feedback for the email button and modal      Let me know if you need further changes     https://ssw-codeauditor-staging-f8357.web.app/build/1425b1d2-902f-44a4-f9db-d1d3723b310c   

 
1. > MODAL INPUT – Reduce the minus red button (to remove current email) in half the size  

   This one was NOT done…

2. MODAL. - It's weird how the underline on "close" goes beyond the text

3. MODAL - "Current Receiving Alerts:" to "Current receiving alerts:"

4. MODAL - Add padding above "Current receiving alerts:"

-- BUTTONS

5. I feel like "Send Email Alerts" and "Compare to Latest Scan" should be next to each other (under the Duration) + use the same button style (black with icon)

6. Add an icon to Compare button https://fontawesome.com/icons/code-compare?f=classic&s=solid

7. I assume if it's the 1st time you're running an URL the Compare button will be disabled. Please confirm

8. Are we able to always hide the "/" at the end of URLs?

9. Can you replace the blue-ish color to be #797979   
    (e.g. that is on "Last scanned: 08 Jun 2023 (about 11 hours ago at 11:59pm)") + on labels "LOAD TEST", "CODE", "LINKS" etc  
    as per https://www.ssw.com.au/ssw/company/Web-Reference.aspx#Colors

10. When you hover this "latest scans" dropdown, the mouse should change to `{cursor: pointer;}`
   Note: Same for the MAIN MENU items links (and any other clickable link )
   
   <img width="464" alt="Screenshot 2023-06-09 at 10 41 49 AM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/55736ff4-e074-42a4-8728-6381aae512d9">

11. The tones of red are inconsistent here. Please fix
   <img width="155" alt="Screenshot 2023-06-09 at 10 43 40 AM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/c0c55b70-2649-4d69-a04b-0b8308416db2">

12. > I'd make the border of the scan darker (from 10% to 50%) on hover so it stands out from the other   
  
    This was part of my previous feedback and was NOT Done yet

14. I think the double arrow works best than single: https://fontawesome.com/icons/angles-right?f=classic&s=solid

15. The icon for broken links 404: https://fontawesome.com/icons/link-slash?f=classic&s=solid

---

- [ ] Please action all the above and send a new version for review

**Comment by tombui99** [comment]
Cc: @jaydenalchin @william-liebenberg @bradystroud @BrookJeynes @hveraus @adamcogan 

Hi @tiagov8 

> MODAL INPUT – Reduce the minus red button (to remove current email) in half the size

Done - as per our conversation, I have replaced it with the trash icon and it will only be displayed if the user hovers it

> MODAL. - It's weird how the underline on "close" goes beyond the text

Done - I have fixed it so it doesn't go beyong

> MODAL - "Current Receiving Alerts:" to "Current receiving alerts:"

Done 

> MODAL - Add padding above "Current receiving alerts:"

Done

-- BUTTONS

> I feel like "Send Email Alerts" and "Compare to Latest Scan" should be next to each other (under the Duration) + use the same button style (black with icon)

Done - I have moved them to stand next to each other under "Duration..."

> Add an icon to Compare button https://fontawesome.com/icons/code-compare?f=classic&s=solid

Done

> I assume if it's the 1st time you're running an URL the Compare button will be disabled. Please confirm

Yes that's correct - it will not show the button if there's no previous scan

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/e7fa0bcd-676a-40c8-ae34-b69049cf0615)

> Are we able to always hide the "/" at the end of URLs?

I chose to keep it to make it consistent with how we store the URLs on the database 

> Can you replace the blue-ish color to be #797979
(e.g. that is on "Last scanned: 08 Jun 2023 (about 11 hours ago at 11:59pm)") + on labels "LOAD TEST", "CODE", "LINKS" etc as per https://www.ssw.com.au/ssw/company/Web-Reference.aspx#Colors

Done

> When you hover this "latest scans" dropdown, the mouse should change to {cursor: pointer;}
Note: Same for the MAIN MENU items links (and any other clickable link )

Done

> The tones of red are inconsistent here. Please fix

Done

> I'd make the border of the scan darker (from 10% to 50%) on hover so it stands out from the other

Done - I made the border darker

> I think the double arrow works best than single: https://fontawesome.com/icons/angles-right?f=classic&s=solid

Done - I've replaced with double arrow

> The icon for broken links 404: https://fontawesome.com/icons/link-slash?f=classic&s=solid

Done - I have replaced all previous icons with this new one

### Screenshots of new UI version

-- Scan Compare

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/8cebe8ca-0b1c-4db2-8cfd-d13657f04356)

-- Email Alert

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/8d11c9f8-ce6e-4ffb-a516-9e9b77310da8)

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/5a51b1be-3893-404d-9475-7122f1a1c87f)

Please let me know if you have any further feedback!

Thanks Tiago!
