### ISSUE TITLE
✨ UI - Navbar and Login screen improvements

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#498]
Cc: @william-liebenberg @adamcogan @tiagov8 

As per my conversation with @tiagov8 , we need to make the following UI changes:

<img width="354" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/1681a55a-089c-47a6-a40d-926b4a3e8852">

- [x] On MAIN MENU + the DROPDOWN MENU - Remove the underline on hover... 
- [x] DROPDOWN MENU - Make the hover red #cc4141
- [x] DROPDOWN MENU - Make all 3 buttons cursor to be pointer 
- [x] DROPDOWN MENU - Change the dark blue background color with some SSW color (see Typography guide AND ask another designer if you get stuck)

<img width="401" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/e8b824da-a768-49cb-912f-f96113f6e854">

- [x] From "Forget..." to "Forgot..."
- [x] Update the logo to NOT have SSW
- [x] Make "USERNAME" in 1 word

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @william-liebenberg @adamcogan 

> On MAIN MENU + the DROPDOWN MENU - Remove the underline on hover...
DROPDOWN MENU - Make the hover red #cc4141
DROPDOWN MENU - Make all 3 buttons cursor to be pointer
DROPDOWN MENU - Change the dark blue background color with some SSW color (see Typography guide AND ask another designer if you get stuck)

All done

<img width="282" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/6aef4045-28be-4127-9991-401fba672e8f">

> From "Forget..." to "Forgot..."
Update the logo to NOT have SSW
Make "USERNAME" in 1 word

All done

<img width="416" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/3a398203-84fc-411a-a7e0-aba472733cc5">

**Comment by tiagov8** [comment]
Hey @tombui99 

The Login button text color should be white.

Please follow https://www.ssw.com.au/ssw/company/Web-Reference.aspx

**Comment by tombui99** [comment]
Hey @tiagov8 
cc @william-liebenberg 

> The Login button text color should be white

Done - I have changed it to white

<img width="419" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/91cc6c1d-ee7c-42be-b11f-a19334783fd3">
