### ISSUE TITLE
♻️ UX - dropdown should open on hover instead of click

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#503]
Hi @tombui99 

### Pain

1. The dropdown menu for CodeAuditor username account should open/hide on hovering, not on click

2. The red bg on hover is showing a red that is NOT SSW's #CC4141

<img width="565" alt="Screenshot 2023-06-20 at 2 48 56 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/4485a326-e8ce-4aaf-9634-a846ea78baf1">

### Tasks
- [x] Make menu open/hide on hover 
- [x] Fix colors

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @adamcogan @william-liebenberg 

> Make menu open/hide on hover
Fix colors

All Done - I have fixed the navbar as requested

<img width="356" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/7e31842d-5833-4e3d-8fa8-41530f0508f7">
