### ISSUE TITLE
♻️ UI/UX - Create a new "How To Use CodeAuditor" page

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#556]
Cc: @adamcogan @william-liebenberg @tiagov8 @zacharykeeping 

Hi @Jord-Gui 

### Pain

As per our conversation, the current homepage is too clustered and that we should move the entire "How It Works" and "How To Use" section to a new page

### Tasks

- [x] Create a new tab "How To Use CodeAuditor" on the menu bar
- [x] Move the entire "How It Works" and "How To Use" to the new page

### Screenshots

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/164d1204-cde0-4af3-95af-125a702915ab)

**Figure: Current CodeAuditor homepage**

Thanks!

**Comment by Jord-Gui** [comment]
Done - How it Works has been moved into it's own tab



![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/41951199/6ee9bd6e-aca9-47c7-87e7-88a2f4f722a4)

Figure: new Home tab and new How it Works tab
