### ISSUE TITLE
♻️ TECH DEBT - Update outdated packages with breaking changes in later version

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#562]
Cc: @bradystroud @william-liebenberg @adamcogan @Jord-Gui @zacharykeeping 
 

### Pain

Over the past weeks, when GitHub dependabots automatically updated some packages, they were causing multiple errors because there were breaking changes introduced in the updates. For example, HTMLHint and Artillery packages.

See https://www.ssw.com.au/rules/packages-up-to-date/

### Tasks

- [x] Run `npm outdated` to see which packages need updating
- [ ] Update packages and Refactor code 

Thanks!

**Comment by zacharykeeping** [comment]
Updated various outdated packages with refactoring as needed including:

dotenv
export-to-csv
firebase
github-markdown-css
query-string
ramda
sirv-cli
slug

**Comment by zacharykeeping** [comment]
Updated some more outdated packages, including:

most rollup packages
firebase-tools
svelte-preprocess
svelte-router-spa
tailwind

Also refactors for changes and cleans up some of the rollup build process.

Seems to cut the final .js output size by ~50% and the final .css output size by ~94%
