### ISSUE TITLE
🐛 Bug - Sign Up button is visible when Logged In

### ISSUE THREAD

**Issue by vladislav-kir** [SSWConsulting/SSW.CodeAuditor#607]
Cc: @adamcogan, @bradystroud, @tombui99, @zacharykeeping, @william-liebenberg 

Hi Team

### Describe the Bug

https://codeauditor.com/home

After I am logged in, I can still see Sign Up button on Home Page

### To Reproduce
1. Go to [Home Page](https://codeauditor.com/home)
2. Login
3. You will still see the Sign Up button on [Home Page](https://codeauditor.com/home)

### Expected Behavior
I expect not to see Sign Up button, if I am already Logged In.

### Tasks
- [x] Investigate
- [x] Fix

### Environment
 - Device: PC
 - Browser: Chrome
 - OS: Windows 11

### Screenshots

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/54652701/eccb1378-6997-47f6-9af4-847f97a5461e)
Figure: Home Page shows Sign Up button, even if I am Logged in

Thanks!

**Comment by zacharykeeping** [comment]
Done - the sign up section is now hidden when logged in.

<img width="1281" alt="Screenshot 2023-08-25 at 4 26 32 pm" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/87f9c3dd-e92c-458d-801f-84550e9ab43e">

**Figure: Sign Up section is hidden when logged in**
