### ISSUE TITLE
🐛 UI - Misalignment in some pages after the deprecated lighthouse CSS file was removed

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#629]
Cc: @william-liebenberg @zacharykeeping @bradystroud @adamcogan 

### Describe the Bug

As per my conversation with @zacharykeeping , we found that after we removed the unused lighthouse.css files, it affects the global css across the site which caused some pages unaligned

### Tasks
- [x] Investigate
- [x] Fix the affected pages

### Screenshots

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/3565cd8a-f9fa-444c-9909-383aed4fb195)

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/ebc72d8d-433c-40f0-ba9d-3ab89f1ec424)

**Figure: unaligned pages**

Thanks!

**Comment by zacharykeeping** [comment]
Done - these pages have been updated to align closer to how they looked previously before lighthouse.css was removed.

<img width="980" alt="Screenshot 2023-09-06 at 4 45 28 pm" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/de3e5f14-a845-407e-af5c-53c4ce6b06c8">

**Figure: Tightened vertical spacing on Scan Results table**

<img width="1002" alt="Screenshot 2023-09-06 at 12 35 36 pm" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/abee76ce-93c5-4a54-8891-5d51e432e3fe">

**Figure: Tightened vertical spacing on Compare Scans**
