### ISSUE TITLE
♻️ UI/UX Improvements - Move Scan History + add tooltip + make width consistent + remove number

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#630]
Cc: @adamcogan 

Hi @tombui99 

### Pain
See the problems:

- **Cyan** - Can we move the History to the 1st column, giving more space to each column
- **Green** - Can we add a tooltip "Scan elapsed time" to this icon (it's not so intuitive what it means)
- **Purple** - The sections are inconsistent aligned
- **Orange** - Is the number "500" necessary? I don't think it brings any value to the user

<img width="1122" alt="Screenshot 2023-09-04 at 12 25 17 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/d53712e9-c84f-4331-9272-39760442784b">

### What code could be improved?
All the above

### Tasks

- [x] Check with the Product Owner what is wanted in the list and action

Thanks!

**Comment by tombui99** [comment]
cc @tiagov8 @jaydenalchin @adamcogan @william-liebenberg @zacharykeeping @Jord-Gui 

> Cyan - Can we move the History to the 1st column, giving more space to each column
Green - Can we add a tooltip "Scan elapsed time" to this icon (it's not so intuitive what it means)
Purple - The sections are inconsistent aligned
Orange - Is the number "500" necessary? I don't think it brings any value to the user

All done - Build List UI has been updated as requested!

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/1a80ea79-86bc-47cd-8de0-0a277c73479e)
