### ISSUE TITLE
♻️ TECH DEBT - move packages to webpack

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#632]
cc @adamcogan @william-liebenberg @zacharykeeping @bradystroud 

As per my conversation with @zacharykeeping , right now we install a lot of packages through CDN as script tags and it is a much better practice to install them to webpack through npm. 

- [x] Install these packages to webpack

**Comment by zacharykeeping** [comment]
Done - all our external references in the UI have been moved to NPM packages using Webpack.
