### ISSUE TITLE
🐛 Working SSW.People link showing as broken

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#640]
Cc: @adamcogan 

Hi @tombui99 

### Describe the Bug
The link https://www.ssw.com.au/people/alumni/rebecca-liu/ is working fine but **showing as broken** on [the latest CodeAuditor run for SSW.Website](https://codeauditor.com/build/7da304b6-4ce9-4cb7-a0d6-5ebb63620ba2):

<img width="1359" alt="Screenshot 2023-09-08 at 3 31 36 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/4a075a27-6703-480a-884d-eb3e1d905a93">

### Tasks
- [x] Investigate
- [x] Fix

### Screenshots

Thanks!

**Comment by tombui99** [comment]
Hey @tiagov8 

From my investigation, it was either a false positive or SSW People was under deployment at the time hence Rebecca's People page was marked as broken. From latest scan however, this site is no longer reported as broken.

See [latest scan on SSW.Website](https://codeauditor.com/build/85018359-1835-4046-f0f0-ce6b6de0fc39)
