### ISSUE TITLE
♻️ UI - Make History Charts clearer by displaying numbers and arranging chart's position

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#649]
Cc: @adamcogan @william-liebenberg @zacharykeeping @tiagov8 

### Pain

As per my conversation with @zacharykeeping and @adamcogan , there's no easy way to see the numbers of errors on that bar chart unless you hover on top of the bar. Additionally, the bar chart is not sorted by importance (Code Errors must be before Code Warnings)

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/c60caa1c-6013-401a-afb0-8abb193babe1)

### Tasks

- [x] Add numbers to the bar chart
- [x] Arrange Code Warnings to be after Code Errors

Thanks!

**Comment by zacharykeeping** [comment]
Done - this has been rearranged and made clearer.

<img width="1099" alt="Screenshot 2023-09-19 at 11 10 24 am" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/2a058bd8-cc35-4346-ad3d-6165212f0e03">

**Figure: Rearranged charts with number count under bars**

**Comment by zacharykeeping** [comment]
Done - this has been rearranged and made clearer.

<img width="1099" alt="Screenshot 2023-09-19 at 11 10 24 am" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/2a058bd8-cc35-4346-ad3d-6165212f0e03">

**Figure: Rearranged charts with number count under bars**
