### ISSUE TITLE
♻️ UI - Improve Ignore URL

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#675]
Cc: @adamcogan @william-liebenberg @zacharykeeping 

### What code could be improved?

- Add help to modal
- Allow ignored links to be edited (add 3 days of ignoration)
- Add some sort of tooltip to what the "ignore" option does

### Tasks

- [x] Implement above changes

Thanks!

**Comment by zacharykeeping** [comment]
Done - these have been implemented.

<img width="649" alt="Screenshot 2023-10-06 at 10 22 26 am" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/f32ba4b3-6174-417c-b716-0bf91eed8ae8">

**Figure: Additional help text in modal**

<img width="1029" alt="Screenshot 2023-10-06 at 10 22 43 am" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/2b07b614-fe1b-4bbd-82e0-76d389f7bd0a">

**Figure: Settings page has a new edit button on ignored URLs**

<img width="1127" alt="Screenshot 2023-10-06 at 10 22 54 am" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/f9de9b79-4ced-4121-b2f2-21f04b37a4e8">

**Figure: Clicking the edit button allows for changing the duration**
