### ISSUE TITLE
🐛 BUG - Broken link not found by CodeAuditor

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#684]
Cc: @adamcogan 

Hi @tombui99 

### Describe the Bug
As per email **Re: Broken Link to RD site**

This link on [About Us](https://www.ssw.com.au/company/about-us) sidebar is broken: 

> [More about Microsoft Regional Director program](http://www.msrd.io/) - http://www.msrd.io/ 

Looking at [the latest SSW.Website scan](https://codeauditor.com/build/208540f7-7084-43cb-a86f-0e6eb4391b59), that broken link was not found by CodeAuditor

### Tasks
- [ ] Investigate why CodeAuditor didn't find it
- [ ] Fix
- [ ] Tell me to fix the link

### Screenshots

<img width="1534" alt="Screenshot 2023-10-04 at 2 41 06 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/3a5daa24-25d8-4170-b57c-11d0281021a3">

Thanks!

**Comment by tiagov8** [comment]
Hey @tombui99 

Another one on https://ssw.com.au/rules/do-you-know-the-correct-way-to-develop-data-entry-forms/ (archived reason)

<img width="1404" alt="Screenshot 2023-10-11 at 3 11 38 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/177c7347-2ed6-4863-883d-6ed6889ac9f4">

**Comment by tiagov8** [comment]
> Would you want me to update CodeAuditor to report any links that does not return 200 status?

yes, I think it should. We have a column for the type of error so we can clearly differentiate them

**Comment by tombui99** [comment]
cc @tiagov8 @adamcogan @william-liebenberg @zacharykeeping 

> CodeAuditor to report any links that does not return successful 2xx status

Done - CodeAuditor is now reporting all broken links that does not return successful 2xx status
