### ISSUE TITLE
✨ Custom Rule - Check for common spelling mistakes

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#693]
Cc: @william-liebenberg @adamcogan @tiagov8 @zacharykeeping 

  
### Pain

As per my conversation with @tiagov8 , we should add a new custom rule that checks for common spelling mistakes as per rule https://ssw.com.au/rules/avoid-common-mistakes/

### Tasks

- [ ] Add a new custom rule that checks these common spelling mistakes

Thanks!

**Comment by tombui99** [comment]
cc @tiagov8 @adamcogan @william-liebenberg @zacharykeeping 

> Add a new custom rule that checks these common spelling mistakes

Done - new custom HTML rule has been added to check common spelling mistakes to comply with rule https://ssw.com.au/rules/avoid-common-mistakes/

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/b7f519dc-a6fa-47e7-b5ec-8cfa9225add9)

**Comment by tiagov8** [comment]
Hey @tombui99 

[The scan on SSW.Rules](https://codeauditor.com/htmlhint/d9372535-dbed-4f47-dd4d-b55a8df8e786) found a bunch of these false positives:

- [ ] 1. Please fix

<img width="1097" alt="Screenshot 2023-10-20 at 5 32 02 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/0f5de5d2-b672-4cd1-86be-79d1cc84f250">

**Comment by tombui99** [comment]
Hi @tiagov8 

> Please fix

Done - Apparently, the reason why it reported the line as an error was because there's a long string before it that contains the word "AKA". I have fixed it so that it will ignore long string and only look for the misspelled words that have space in between

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/dd2ab5b4-04e3-43cb-9f7e-13ef3fa86f5a)

**Figure: Unit test that checks for misspelled words in long string**
