### ISSUE TITLE
♻️ UI - Notify when a scan is outdated

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#724]
Cc: @BrookJeynes @adamcogan @william-liebenberg @tiagov8 @zacharykeeping 

### Pain

As per my conversation with @BrookJeynes, he would love to know if he was on the latest scan or not. Therefore, a warning at the top of the page when on an outdated scan that links to the latest one would be very helpful.

### Tasks

- [ ] Add a warning to top of the page if the scan is outdated
- [ ] This warning should link to the latest scan of that Url 

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @BrookJeynes 

I have got the initial design for the new button that takes to the latest scan

1. Let me know if you have any feedback regarding this UI

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/d8063440-edcc-4269-b397-b4ad126ba7ba)

**Comment by tiagov8** [comment]
cc @jaydenalchin 

Hi @tombui99 

IMO the 3 buttons with the same weight are too much in this page...

My recommendation is to 

1. Keep "Go to latest scan" the black one (primary)
2. Then make the other 2 secondary (keep them white bg with black border and text/icon)
3. Use that order Primary / Secondary / Seconday
4. Change from 'Last scanned:' to 'Scanned on'. I think the word "last" there might be confused with "latest"

**Comment by tombui99** [comment]
Hey @tiagov8 
cc @jaydenalchin @BrookJeynes 

Thanks for your feedback!

> 1. Keep "Go to latest scan" the black one (primary)
> 2. Then make the other 2 secondary (keep them white bg with black border and text/icon)
> 3. Use that order Primary / Secondary / Seconday
> 4. Change from 'Last scanned:' to 'Scanned on'. I think the word "last" there might be confused with "latest"

All done - Let me know what you approve this UI

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/72bd3f78-ef69-4845-992c-b37af0f002c0)

**Comment by tiagov8** [comment]
I think it's good enough.

@BrookJeynes What are your thoughts?

To make it even more clear we could add a ⚠️ OR 🦖 before the text "Scanned on..."

**Comment by jaydenalchin** [comment]
@tiagov8 @tombui99 
Please no emojis 😅 
1. I would make the border/outline of secondary buttons just slightly thicker, but otherwise looks fantastic.

**Comment by tiagov8** [comment]
> Please no emojis 😅

![200w](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/71eb6fbe-f8af-4009-8487-62ee551c9d1d)

**Comment by tombui99** [comment]
Done - I have added the button as per feedback

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/0619d240-47ed-4a97-94dc-4b318d3f9f9e)
