### ISSUE TITLE
🐛 BUG - Enable/Disable Rules button inactive when logged out

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.CodeAuditor#731]
Cc: @tombui99 @william-liebenberg @BrookJeynes 

Hi team

### Describe the Bug

As per our discussion with @BrookJeynes, we discovered that the Enable/Disable Rules button displays when logged out but does nothing when clicked. This should either be hidden when logged out or should alert the user to log in to use this functionality.

### Tasks
- [x] Investigate
- [x] Fix

### Screenshots

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/35260d3f-96f5-46fc-bf3d-1ad278fa0e69)

**Figure: The Enable/Disable button is shown when not logged in but does nothing when clicked**

Thanks!

**Comment by zacharykeeping** [comment]
Done - this following buttons are now hidden when logged out:

Enable/Disable Rules
Set Performance Threshold For Next Scan
Send Email Alerts

**Comment by tombui99** [comment]
- [ ] Reimplement these buttons and add a toast to notify user to log in or sign up

**Comment by tombui99** [comment]
>  Reimplement these buttons and add a toast to notify user to log in or sign up

Done - Toast added to notify user to login or signup in order to access certain features

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/309d7daa-f798-49b0-9f72-4d56b2c63058)

**Comment by tombui99** [comment]
- [ ] Fix alignment on Toast
