### ISSUE TITLE
✨ Add a tagline

### ISSUE THREAD

**Issue by Jord-Gui** [SSWConsulting/SSW.CodeAuditor#772]
Cc: @adamcogan @zacharykeeping @william-liebenberg 

Hi @tombui99 

### Pain

As per my conversation with @adamcogan, GitHub is spelled wrong. It would also be cool to have a tagline underneath the GitHub section to give a succint summary of what Code Auditor does. Something like “Find the problems/gremlins in your website”

### Tasks

- [x] Change "Github" to GitHub"
- [x] Add a tagline underneath the GitHub icon

### Screenshots

<img width="1456" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/41951199/0fcd1b73-9fdc-47e3-b233-08ab0b2be19c">\
**Figure: Code Auditor homepage**

Thanks!

**Comment by tombui99** [comment]
cc @adamcogan @zacharykeeping @william-liebenberg @tiagov8 @jaydenalchin 

Hi @Jord-Gui 

> Change "Github" to GitHub"
 Add a tagline underneath the GitHub icon

All done - new Homepage UI has been updated as requested from designers

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/5f17225d-8f66-4cc6-a187-0c4fb94f445d)
