### ISSUE TITLE
♻️ UI - Custom Rule Options should show default values

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.CodeAuditor#786]
Cc: @tombui99 @william-liebenberg 

Hi team

### Pain

While playing with the new custom rule options, I noticed that updating rules options with existing defaults can be confusing. For example, when updating the custom option for "Content - Avoid common spelling and syntax mistakes", if you add new terms to report it will override the existing list, and it's not obvious this happens and what the existing terms were without clicking through to the rule. This should be updated to pre-fill these custom options with the existing default values to make this easier to work with.

### Tasks

- [x] Investigate
- [x] Implement solution

### Screenshots

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/11373951-28a5-414b-a7a6-99ec6a3e4544)

**Figure: It's not obvious here what the default terms are, and that adding a term here will replace the default list**

Thanks!

**Comment by zacharykeeping** [comment]
Done - this has been implemented.

<img width="671" alt="Screenshot 2023-11-24 at 11 29 46 am" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/56be8835-f817-4492-9e93-b05bf3aeaa33">

**Figure: Default options are now shown and can be modified**

**Comment by tombui99** [comment]
- [ ] Redesign fields to put the list into a scrollable div
