### ISSUE TITLE
♻️ CodeAuditor Workflow - Configure permission for GitHub tokens

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#801]
cc @adamcogan @william-liebenberg @wicksipedia 

As per my conversation with @wicksipedia , there are some adjustments we need to make on CodeAuditor Workflow:
- [x] Use default `github.token` instead of making users manually provide theirs
- [x] Set permission for the token to be able to create issue

**Comment by wicksipedia** [comment]
as per Teams have a look at:

Configuring permissions - https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

Here's an issue action (and the sample uses permission assignment)
https://github.com/JasonEtco/create-an-issue

Here's another action that can create an issue which is a little more flexible
https://github.com/marketplace/actions/create-github-issue

**Comment by tombui99** [comment]
cc @adamcogan @william-liebenberg 

Hi @wicksipedia 

> Use default github.token instead of making users manually provide theirs

Done 

> Set permission for the token to be able to create issue

Done 

<img width="750" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/8b4ce126-b8b5-4871-8b86-078f70e70e40">

**Figure: Updated example usage to use `github.token` and set permission to write issue**
