### ISSUE TITLE
♻️ Custom Rule - Check Auth terms

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#830]
cc @adamcogan @matt-goldman @tiagov8 @william-liebenberg 
To @tombui99 

### Pain

As per my call with @adamcogan @matt-goldman @tiagov8 , we need to add a new custom rule to CodeAuditor that:
- Remove the existing rule about using "log in" instead of "login"
- Finds "log in" (with spaces)
- Finds "log on" or "logon" 
- Suggests changing "log in" to "sign in"

### Tasks

- [ ] Implement the change

Thanks!

**Comment by tiagov8** [comment]
Hi @tombui99 

I think we also need a task to remove the other rule that talks about "log in" instead of "login". It's leading people to mistakes and the reason for the new rule to be created

**Comment by tombui99** [comment]
> Remove the existing rule about using "log in" instead of "login"
Finds "log in" (with spaces)
Finds "log on" or "logon"
Suggests changing "log in" to "sign in"

All done - I have added a new custom rule that checks and suggests these authentication terms

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/d3bb6133-4624-4e50-8cb2-982d3a7f7b25)

**Figure: New custom rule added**
