### ISSUE TITLE
✨ Custom rule - greyboxes/email templates need line breaks before ":::"

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#854]
Cc: @bradystroud @adamcogan 

Hi @tombui99 
  
### Pain
We have custom "classes" if you will in our Rules Markdown. For example, to add a greybox:

```
::: greybox
{{ TEXT }}
:::
```

❌ That **won't** work if you have a sentence right before it without a line break. E.g.

```
Some sentence.
::: greybox
{{ TEXT }}
:::
```

✅ The fix it, the line break must exist. E.g.

```
Some sentence.

::: greybox
{{ TEXT }}
:::
```

See an example of a broken rule that I fixed with Adam: https://github.com/SSWConsulting/SSW.Rules.Content/pull/8099

### Suggested Solution

- [ ] 1. Can CodeAuditor check for the source Markdown of these pages and look for these errors?

**Note:** I think CodeAuditor **only** reads HTML as the browser, but we want to know if the above is possible.

---

<img width="960" alt="Screenshot 2024-03-08 at 1 09 59 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/9db37dd1-1d0c-415a-893a-79807140c987">

**Figure: The broken greybox we found**

**Comment by tombui99** [comment]
cc @adamcogan @william-liebenberg 

Hey @tiagov8 

As per our conversation, we are working on a Markdown Auditor that will make this possible by checking all markdown files in a PR. 

See https://github.com/SSWConsulting/SSW.CodeAuditor/issues/855

This is to make sure we have this implemented on the new "Auditor" when it's ready.
