### ISSUE TITLE
🐛 Validation | Non-lowercase attribute rule should be ignored for SVG

### ISSUE THREAD

**Issue by andrewwaltosssw** [SSWConsulting/SSW.CodeAuditor#878]
Cc: @tombui99 

Hi Tom

### Describe the Bug

Report shows Code Error for SVG element violating lowercase attribute [rule](https://htmlhint.com/docs/user-guide/rules/attr-lowercase) however the rule states that camelCase in SVG elements should not be a violation.

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/87786621/b494f943-bee6-4c6c-8aa2-ee97d1a02d62)
**Figure: Screenshot of code snippet tagged for violating lowercase attribute rule**

### To Reproduce
1. Go to https://codeauditor.com/htmlhint/6a99477f-c494-4705-5fe1-6e3be7823f72
2. Click on:
![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/87786621/becf93df-1994-42be-9bc4-8a46d7e253df)
**Figure: screenshot of Code results pointing to SVG element violation**
3. See error

### Expected Behavior

Expecting SVG elements to not raise this error type

### Tasks
- [x] Investigate
- [x] Fix

### Environment
 - Device: MacBook
 - Browser: Edge
 - OS: Sonoma

Thanks!

**Comment by tombui99** [comment]
cc: @william-liebenberg @adamcogan 

As per my conversation with @william-liebenberg , because this HTML rule comes default with the library, we have no control over it; therefore, we would need to rewrite a new custom rule on our end.

To myself,

- [ ] Rewrite the HTML rule and add it as a custom one

**Comment by tombui99** [comment]
cc @andrewwaltosssw @william-liebenberg @adamcogan 

> Investigate and Fix

Done - Custom rule was configured to ignore known properties of SVG such as "viewBox" which is no longer reported 

See latest scan on https://tina.io/
https://codeauditor.com/htmlhint/6e05cf30-a328-4ae1-d68a-e0ed5494d0c8
