### ISSUE TITLE
🐛 Validation | Warning URL link to root should be ignored

### ISSUE THREAD

**Issue by andrewwaltosssw** [SSWConsulting/SSW.CodeAuditor#879]
Cc: @tombui99 

Hi Tom

### Describe the Bug

Report shows Code Warning for violating [Links - URLs should not include full stop or slash at the end](https://ssw.com.au/rules/no-full-stop-or-slash-at-the-end-of-urls/) however there are cases where we use a single slash to reference the root URL

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/87786621/75062a00-5700-4382-81fa-c67e0823c900)
**Figure: Screenshot of code snippet tagged for violating URL ending in slash rule**

### To Reproduce
1. Go to https://codeauditor.com/htmlhint/6a99477f-c494-4705-5fe1-6e3be7823f72
2. Click on:
![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/87786621/60c3acc3-1711-4347-99ce-8afd1cf98003)
**Figure: screenshot of Code results pointing to SVG element violation**
3. See error

### Expected Behavior

Expecting references to root to not raise this error type

### Tasks
- [x] Investigate
- [x] Fix

### Environment
 - Device: MacBook
 - Browser: Edge
 - OS: Sonoma

Thanks!

**Comment by tombui99** [comment]
cc @andrewwaltosssw @adamcogan @william-liebenberg 

> Investigate and Fix

**Comment by tombui99** [comment]
cc @andrewwaltosssw @adamcogan @william-liebenberg 

> Investigate and Fix

Done - Custom rule was fixed to ignore root urls `/`

See latest scan on https://tina.io/ where the false positive is no longer reported
https://codeauditor.com/htmlhint/6e05cf30-a328-4ae1-d68a-e0ed5494d0c8?displayMode=0
