### ISSUE TITLE
💄 UI - Scan History graph

### ISSUE THREAD

**Issue by christianmorfordwaitessw** [SSWConsulting/SSW.CodeAuditor#89]
To: @tombui99 
Cc: @nvhoanganh @adamcogan 

Looking at the history graph of the scans it's hard to know which is the latest one. Is it the far left bar or far right bar?

Can you please add some indicator or make it obvious which bar on the history graph is the last scan.
1. Put a black dot under the bar of the last scan.
2. Change the text from “HISTORY” to “HISTORY -->“.
 
![image](https://user-images.githubusercontent.com/56522256/96537913-1ab6dd00-12e3-11eb-90b5-47ced51cdc15.png)  
**Figure: Latest CodeAuditor scan https://codeauditor.com/build/9681199c-7d58-46c2-ede6-0997fc854504**

-Christian

**Comment by tombui99** [comment]
Hi Christian,

The latest scan is the far right bar. I will implement the changes to make it clearer.

Thank you,
Tom
