### ISSUE TITLE
💄 UI - Ensure Menu displays on a single line

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.CodeAuditor#941]
@adamcogan @tiagov8 @zacharykeeping 

**Description**
https://codeauditor.com/
The current layout of the menu on the CodeAuditor website shows the menu items split across two lines, with "Contact SSW" breaking into two lines. This affects the visual consistency and user experience.

**Acceptance Criteria**
- The entire menu, including "Contact SSW," is displayed on a single line without breaking.
- Ensure the design is responsive across different screen sizes, maintaining the single-line menu layout.

**Tasks**
- [x] Adjust the menu layout to fit all items on one line.
- [x] Test the menu on various screen resolutions to ensure responsiveness.

**Screenshot**
![Image](https://github.com/user-attachments/assets/c510de14-80e4-4213-b2fc-22b5ebfcd1e3)
**Figure: "Contact SSW" should be fully visible on one line**

**Comment by tiagov8** [comment]
cc @adamcogan @zacharykeeping 

Done ✅

**Comment by tiagov8** [comment]
PR: https://github.com/SSWConsulting/SSW.CodeAuditor/pull/945
