### ISSUE TITLE
💄 Rules to better navigation - 4 rules

### ISSUE THREAD

**Issue by adamcogan** [SSWConsulting/SSW.CodeAuditor#96]
I noticed that the rollover is missing from the URL so:
1. Review the first 4 rules on https://rules.ssw.com.au/rules-to-better-websites-navigation
2. Which of them is CodeAuditor not compliant with?
3. Please fix

**Comment by tombui99** [comment]
Hi Adam,

1. done
2. done - CodeAuditor was not compliant with rule 2
3. done

**Comment by adamcogan** [comment]
Great 👍
