### ISSUE TITLE
✨ Show all public scans

### ISSUE THREAD

**Issue by adamcogan** [SSWConsulting/SSW.CodeAuditor#97]
Encourage users to log in - here is one way

1. Change text
>Showing last 100 public scans completed by all users
to
>Showing last 100 public scans - See all

2. Make the 'See all' be a link

3. When you click on this it makes you log in (for free)

**Comment by tombui99** [comment]
Hi Adam,

1. done
2. done
3. done

**Comment by tombui99** [comment]
Hi Adam,

This is the updated changes according to your request

1. Done
![image](https://user-images.githubusercontent.com/67776356/99342562-46c47e80-28e0-11eb-8446-e9198881a999.png)
**Figure: Changed text to "Showing last 100 public scans - See all**

2. Done
![image](https://user-images.githubusercontent.com/67776356/99342562-46c47e80-28e0-11eb-8446-e9198881a999.png)
**Figure: 'See all' being a link**

3. Done - When 'See All' is clicked, it navigates to the Log In screen

**Comment by adamcogan** [comment]
Hi @tombui99 
   CC: @christianmorfordwaitessw 

Not done 
1. Add dotted line under the urls eg. See All
2. Change from
    Show all Scan
   To
    Showing all xxx public scans
-a
www.adamcogan.com

**Comment by tombui99** [comment]
Hi @adamcogan 
CC: @christianmorfordwaitessw 

> 1. Add dotted line under the urls eg. See All
- Done
> 2. Change from
Show all Scan
To
Showing all xxx public scans
- Done
![image](https://user-images.githubusercontent.com/67776356/100027808-a6bba780-2e41-11eb-9518-cd4b3371d6f7.png)
**Figure: Link to "Showing all xxx public scans"**
