### ISSUE TITLE
💄 When seeing all scans show the date and time as the first field

### ISSUE THREAD

**Issue by adamcogan** [SSWConsulting/SSW.CodeAuditor#98]
![image](https://user-images.githubusercontent.com/1222712/98750508-445eb200-2412-11eb-8e1e-8074f27861f5.jpeg)

1. When you click the down arrow - show the count next to it
2. When it expands move the date and time to be first (from the image the time needs to be moved up)
3. Add a space before the AM/PM 
Eg. Change from
01:43PM to 1:43 PM
-a

**Comment by tombui99** [comment]
Hi Adam,

1. done
2. done
3. done

**Comment by adamcogan** [comment]
Hi @tombui99  
It is looking better
1. Indent 
2. Same font

-a
![image](https://user-images.githubusercontent.com/1222712/99936853-42a0d100-2db8-11eb-99ae-6358e2452da2.jpeg)

**Comment by tombui99** [comment]
Hi @adamcogan 

> 1. Indent
- Done
> 2. Same font
- Done
![image](https://user-images.githubusercontent.com/67776356/100027923-e1254480-2e41-11eb-9f78-cdc191d078ab.png)
**Figure: Build List with same font and indentation**
